-- 献立マスタ。easy / normal は各ジャンル40件、elaborate は各ジャンル10件（計360件）。
--
-- 週間献立で7日分を重複なく引くため、(genre, difficulty) の組み合わせごとに
-- 最低10件を確保する。id は gen_random_uuid() で採番し、name の UNIQUE 制約と
-- ON CONFLICT DO NOTHING により再実行しても重複しない（冪等）。
--
-- **2026-07-22: easy / normal を各10件から40件に増やしている（ジャンル単位で順次）。**
-- 「献立が少なすぎる。特に簡単・普通を増やしたい」という要望による。
-- elaborate を10件のまま据え置くのは、利用者レビューで「高価・入手困難なものが混ざる」と
-- 指摘があり（task.md「利用者レビューからの後続タスク」C）、日常的に作れる献立の
-- 比率を上げたいため。期待件数は backend/internal/db/seed_test.go が正。
--
-- **2026-07-23: role（主菜 / 副菜 / 汁物）を付与した（spec.md 2.10）。**
-- 大半は main で、side 30件・soup 15件。単品で夕食が成立するかを基準にしており、
-- 丼・麺・鍋・定食は main に置く（親子丼やラーメンは主食を兼ねるが一食になる）。
-- **この分類は主観が入るため ON CONFLICT の更新対象に含めている。**
-- 見直したらシードを流し直せば既存行にも反映される。

INSERT INTO menus (id, name, name_kana, genre, difficulty, role, description) VALUES
-- ============ 和食 × 簡単 ============
(gen_random_uuid(), '親子丼',        'おやこどん',        'japanese', 'easy', 'main', '鶏肉と卵を甘辛い出汁でとじた定番の丼もの'),
(gen_random_uuid(), '豚の生姜焼き',   'ぶたのしょうがやき',  'japanese', 'easy', 'main', '生姜の効いたタレで豚肉を焼く、ご飯が進む一品'),
(gen_random_uuid(), '鮭の塩焼き',     'さけのしおやき',     'japanese', 'easy', 'main', '塩を振って焼くだけ。魚料理の入り口として手軽'),
(gen_random_uuid(), '牛丼',          'ぎゅうどん',        'japanese', 'easy', 'main', '玉ねぎと牛肉を甘辛く煮てご飯にのせる'),
(gen_random_uuid(), 'かつ丼',        'かつどん',          'japanese', 'easy', 'main', '揚げたとんかつを卵でとじた満足感のある丼'),
(gen_random_uuid(), '肉じゃが',      'にくじゃが',        'japanese', 'easy', 'main', 'じゃがいもと牛肉を出汁で煮込んだ家庭料理の代表'),
(gen_random_uuid(), 'だし巻き卵定食', 'だしまきたまごていしょく', 'japanese', 'easy', 'main', 'ふんわりした卵焼きを主役にした軽めの定食'),
(gen_random_uuid(), 'きつねうどん',   'きつねうどん',      'japanese', 'easy', 'main', '甘く煮た油揚げをのせた出汁の効いたうどん'),
(gen_random_uuid(), 'ざるそば',      'ざるそば',          'japanese', 'easy', 'main', '茹でて冷水で締めるだけ。暑い日に向く'),
(gen_random_uuid(), '鶏の照り焼き',   'とりのてりやき',     'japanese', 'easy', 'main', '甘辛いタレを絡めて照りよく仕上げた鶏もも肉'),
-- ここから 2026-07-22 追加分（和食 × 簡単を10件→40件）
(gen_random_uuid(), '鯖の塩焼き',     'さばのしおやき',     'japanese', 'easy', 'main', '振り塩をして焼くだけ。青魚の脂が旨味になる'),
(gen_random_uuid(), 'さんまの塩焼き',  'さんまのしおやき',    'japanese', 'easy', 'main', '丸ごと焼いて大根おろしを添える。秋の定番'),
(gen_random_uuid(), 'あじの開き定食',  'あじのひらきていしょく', 'japanese', 'easy', 'main', '干物を焼くだけで一食になる。朝食にも向く'),
(gen_random_uuid(), 'ぶりの照り焼き',  'ぶりのてりやき',     'japanese', 'easy', 'main', 'タレを絡めて焼く。切り身なので下処理が要らない'),
(gen_random_uuid(), '鮭のホイル焼き',  'さけのほいるやき',    'japanese', 'easy', 'main', '包んで蒸し焼きにするだけ。洗い物も少ない'),
(gen_random_uuid(), 'いわしの梅煮',    'いわしのうめに',     'japanese', 'easy', 'main', '梅と生姜で青魚の臭みを抜きながら煮る'),
(gen_random_uuid(), '豚丼',          'ぶたどん',          'japanese', 'easy', 'main', '豚バラと玉ねぎを甘辛く煮てご飯にのせる'),
(gen_random_uuid(), '焼き鳥丼',      'やきとりどん',      'japanese', 'easy', 'main', '焼いた鶏とねぎをタレごとご飯にのせる'),
(gen_random_uuid(), '玉子丼',        'たまごどん',        'japanese', 'easy', 'main', '玉ねぎと卵だけ。冷蔵庫が寂しい日に'),
(gen_random_uuid(), '海鮮丼',        'かいせんどん',      'japanese', 'easy', 'main', '刺身を切って酢飯にのせるだけ。火を使わない'),
(gen_random_uuid(), 'ねぎとろ丼',     'ねぎとろどん',      'japanese', 'easy', 'main', 'まぐろとねぎを混ぜてのせる。手間がほぼ無い'),
(gen_random_uuid(), 'しらす丼',      'しらすどん',        'japanese', 'easy', 'main', 'しらすと卵黄をのせる。5分で用意できる'),
(gen_random_uuid(), '月見うどん',     'つきみうどん',      'japanese', 'easy', 'main', '温かい出汁に卵を落とすだけ'),
(gen_random_uuid(), '肉うどん',      'にくうどん',        'japanese', 'easy', 'main', '甘辛く煮た牛肉をうどんにのせる'),
(gen_random_uuid(), '焼きうどん',     'やきうどん',        'japanese', 'easy', 'main', '茹で麺と余り野菜を炒め合わせる'),
(gen_random_uuid(), 'ぶっかけうどん',  'ぶっかけうどん',     'japanese', 'easy', 'main', '冷たい麺に濃いめの出汁をかける。薬味で変化を付ける'),
(gen_random_uuid(), 'とろろそば',     'とろろそば',        'japanese', 'easy', 'main', 'すりおろした長芋をかけるだけ。食欲が無い日にも'),
(gen_random_uuid(), 'そうめん',      'そうめん',          'japanese', 'easy', 'main', '茹で時間が短く、暑い日の昼食に向く'),
(gen_random_uuid(), '野菜炒め',      'やさいいため',      'japanese', 'easy', 'side', '冷蔵庫の野菜を使い切れる。強火で手早く'),
(gen_random_uuid(), 'なすの味噌炒め',  'なすのみそいため',    'japanese', 'easy', 'side', '油を吸わせた茄子に味噌ダレを絡める'),
(gen_random_uuid(), '豚バラ大根',     'ぶたばらだいこん',    'japanese', 'easy', 'main', '煮るだけで大根に肉の旨味が染みる'),
(gen_random_uuid(), '鶏肉と大根の煮物', 'とりにくとだいこんのにもの', 'japanese', 'easy', 'main', '鍋に入れて煮るだけ。作り置きにも向く'),
(gen_random_uuid(), '厚揚げの煮物',   'あつあげのにもの',    'japanese', 'easy', 'side', '下ごしらえ不要。あと一品欲しい日に'),
(gen_random_uuid(), 'きんぴらごぼう定食', 'きんぴらごぼうていしょく', 'japanese', 'easy', 'main', '根菜を細切りにして炒め煮にする常備菜の定食'),
(gen_random_uuid(), 'ピーマンの肉詰め', 'ぴーまんのにくづめ',  'japanese', 'easy', 'main', '詰めて焼くだけ。ピーマンが苦手でも食べやすい'),
(gen_random_uuid(), 'つくね',        'つくね',            'japanese', 'easy', 'main', 'こねて焼いてタレを絡める。卵黄を添えても'),
(gen_random_uuid(), '豆腐ハンバーグ',  'とうふはんばーぐ',    'japanese', 'easy', 'main', '豆腐でかさを増やした軽い口当たりの一品'),
(gen_random_uuid(), '鶏むね肉のさっぱり煮', 'とりむねにくのさっぱりに', 'japanese', 'easy', 'main', '酢で煮るので安い胸肉でも柔らかく仕上がる'),
(gen_random_uuid(), '冷しゃぶ',      'ひやしゃぶ',        'japanese', 'easy', 'main', '茹でて冷やすだけ。野菜と一緒に食べられる'),
(gen_random_uuid(), 'お好み焼き',     'おこのみやき',      'japanese', 'easy', 'main', 'キャベツを刻んで混ぜて焼く。粉ものの定番'),

-- ============ 和食 × 普通 ============
(gen_random_uuid(), '筑前煮',        'ちくぜんに',        'japanese', 'normal', 'main', '根菜と鶏肉を出汁で含め煮にした滋味深い煮物'),
(gen_random_uuid(), '鯖の味噌煮',     'さばのみそに',      'japanese', 'normal', 'main', '味噌と生姜で青魚の風味を活かして煮る'),
(gen_random_uuid(), '豚汁定食',      'とんじるていしょく',  'japanese', 'normal', 'main', '具だくさんの豚汁を主役にした定食'),
(gen_random_uuid(), '鶏の唐揚げ',     'とりのからあげ',     'japanese', 'normal', 'main', '下味を付けて二度揚げする、外はカリッと中はジューシー'),
(gen_random_uuid(), '茶碗蒸し',      'ちゃわんむし',      'japanese', 'normal', 'side', '出汁と卵の配合と蒸し加減が仕上がりを左右する'),
(gen_random_uuid(), 'ぶり大根',      'ぶりだいこん',      'japanese', 'normal', 'main', 'ぶりの旨味を大根に含ませた冬の煮物'),
(gen_random_uuid(), 'かぼちゃの煮物',  'かぼちゃのにもの',   'japanese', 'normal', 'side', '煮崩れさせずに味を含ませるのがコツ'),
(gen_random_uuid(), '手巻き寿司',     'てまきずし',        'japanese', 'normal', 'main', '酢飯と具材を用意して各自で巻く。人が集まる日に'),
(gen_random_uuid(), '鶏そぼろ丼',     'とりそぼろどん',     'japanese', 'normal', 'main', '鶏そぼろと炒り卵を彩りよく盛った二色丼'),
(gen_random_uuid(), 'いなり寿司',     'いなりずし',        'japanese', 'normal', 'main', '甘辛く煮た油揚げに酢飯を詰める'),
-- ここから 2026-07-22 追加分（和食 × 普通を10件→40件）
(gen_random_uuid(), '豚の角煮',      'ぶたのかくに',      'japanese', 'normal', 'main', '下茹でしてから煮含める。時間はかかるが手順は単純'),
(gen_random_uuid(), '肉豆腐',        'にくどうふ',        'japanese', 'normal', 'main', '牛肉と焼き豆腐を割下で煮る。すき焼きより手軽'),
(gen_random_uuid(), 'とんかつ',      'とんかつ',          'japanese', 'normal', 'main', '衣を付けて揚げる。厚みに合わせた火加減が要る'),
(gen_random_uuid(), 'とり天',        'とりてん',          'japanese', 'normal', 'main', '下味を付けた鶏を天ぷら衣で揚げる大分の郷土料理'),
(gen_random_uuid(), 'チキン南蛮',     'ちきんなんばん',     'japanese', 'normal', 'main', '揚げた鶏を甘酢に浸し、タルタルソースを添える'),
(gen_random_uuid(), '鯖の竜田揚げ',   'さばのたつたあげ',    'japanese', 'normal', 'main', '下味を染み込ませてから揚げる。青魚が食べやすくなる'),
(gen_random_uuid(), 'あじの南蛮漬け',  'あじのなんばんづけ',  'japanese', 'normal', 'main', '揚げた魚を野菜ごと甘酢に漬ける。冷やしても旨い'),
(gen_random_uuid(), '豚肉の味噌漬け焼き', 'ぶたにくのみそづけやき', 'japanese', 'normal', 'main', '前日に漬けておけば焼くだけ。焦げやすいので弱火で'),
(gen_random_uuid(), '揚げ出し豆腐',   'あげだしどうふ',     'japanese', 'normal', 'side', '豆腐の水切りと出汁あんの加減で仕上がりが決まる'),
(gen_random_uuid(), 'なすの煮浸し',   'なすのにびたし',     'japanese', 'normal', 'side', '素揚げしてから出汁に浸す。冷やして翌日でも'),
(gen_random_uuid(), '里芋の煮っころがし', 'さといものにっころがし', 'japanese', 'normal', 'side', 'ぬめりを取ってから照りが出るまで煮絡める'),
(gen_random_uuid(), 'ふろふき大根',   'ふろふきだいこん',    'japanese', 'normal', 'side', '米のとぎ汁で下茹でし、味噌だれをかける'),
(gen_random_uuid(), 'いか大根',      'いかだいこん',      'japanese', 'normal', 'main', 'いかの旨味を大根に移す。煮すぎると硬くなる'),
(gen_random_uuid(), 'いわしのつみれ汁', 'いわしのつみれじる',  'japanese', 'normal', 'soup', '身を叩いて団子にする。魚をさばく練習にもなる'),
(gen_random_uuid(), 'けんちん汁定食',  'けんちんじるていしょく', 'japanese', 'normal', 'main', '根菜と豆腐を炒めてから煮る具だくさんの汁物'),
(gen_random_uuid(), '天丼',          'てんどん',          'japanese', 'normal', 'main', '揚げたてにタレをくぐらせてご飯にのせる'),
(gen_random_uuid(), 'かき揚げ丼',     'かきあげどん',      'japanese', 'normal', 'main', '細切りの具をまとめて揚げる。散らさないのがコツ'),
(gen_random_uuid(), '天ぷらうどん',   'てんぷらうどん',     'japanese', 'normal', 'main', '海老天を温かいうどんにのせる'),
(gen_random_uuid(), '鍋焼きうどん',   'なべやきうどん',     'japanese', 'normal', 'main', '土鍋で具ごと煮る。寒い日に一人分から作れる'),
(gen_random_uuid(), 'だし茶漬け',     'だしちゃづけ',      'japanese', 'normal', 'main', '出汁の取り方がそのまま味になる。〆にも'),
(gen_random_uuid(), '五目炊き込みご飯', 'ごもくたきこみごはん', 'japanese', 'normal', 'main', '具材と米を一緒に炊く。水加減が要注意'),
(gen_random_uuid(), '鯛めし',        'たいめし',          'japanese', 'normal', 'main', '鯛を焼いてから米と炊き、身をほぐして混ぜる'),
(gen_random_uuid(), 'ちらし寿司',     'ちらしずし',        'japanese', 'normal', 'main', '具を別々に煮て酢飯に散らす。行事食にも'),
(gen_random_uuid(), '太巻き',        'ふとまき',          'japanese', 'normal', 'main', '具を並べて巻く。切り口を揃えるのが難しい'),
(gen_random_uuid(), 'おでん',        'おでん',            'japanese', 'normal', 'main', '種ごとに火の通り方が違うので入れる順に気を配る'),
(gen_random_uuid(), '湯豆腐',        'ゆどうふ',          'japanese', 'normal', 'side', '昆布出汁で温めるだけ。豆腐と薬味の質が出る'),
(gen_random_uuid(), '鶏団子鍋',      'とりだんごなべ',     'japanese', 'normal', 'main', 'ひき肉を練って落とす。締めの雑炊まで楽しめる'),
(gen_random_uuid(), '寄せ鍋',        'よせなべ',          'japanese', 'normal', 'main', '魚介と野菜を出汁で炊き合わせる'),
(gen_random_uuid(), '石狩鍋',        'いしかりなべ',      'japanese', 'normal', 'main', '鮭と根菜を味噌仕立てにした北海道の鍋'),
(gen_random_uuid(), 'きりたんぽ鍋',   'きりたんぽなべ',     'japanese', 'normal', 'main', 'つぶした米を棒状にして鶏の出汁で煮る秋田の鍋'),

-- ============ 和食 × 手が込んだ ============
(gen_random_uuid(), '天ぷら盛り合わせ', 'てんぷらもりあわせ',  'japanese', 'elaborate', 'main', '衣の温度管理と揚げ油の見極めが要る'),
(gen_random_uuid(), '握り寿司',      'にぎりずし',        'japanese', 'elaborate', 'main', 'ネタの仕込みとシャリの加減に技術が要る'),
(gen_random_uuid(), '鰻の蒲焼き',     'うなぎのかばやき',   'japanese', 'elaborate', 'main', 'タレを重ねながら焼き上げる。下処理も手間'),
(gen_random_uuid(), 'すき焼き',      'すきやき',          'japanese', 'elaborate', 'main', '割下の配合と具材を入れる順序で味が決まる'),
(gen_random_uuid(), 'しゃぶしゃぶ',   'しゃぶしゃぶ',      'japanese', 'elaborate', 'main', '出汁とタレを揃え、肉と野菜を順に楽しむ'),
(gen_random_uuid(), 'おせち料理',     'おせちりょうり',     'japanese', 'elaborate', 'main', '多数の品を一つずつ仕込む。数日がかりの献立'),
(gen_random_uuid(), '土瓶蒸し',      'どびんむし',        'japanese', 'elaborate', 'soup', '松茸と鱧を土瓶で蒸した、出汁を味わう秋の一品'),
(gen_random_uuid(), '鯛の姿造り',     'たいのすがたづくり',  'japanese', 'elaborate', 'main', '一尾をさばいて盛り付ける。包丁の技術が要る'),
(gen_random_uuid(), '松花堂弁当',     'しょうかどうべんとう', 'japanese', 'elaborate', 'main', '四つ切りの器に複数の料理を彩りよく詰める'),
(gen_random_uuid(), '鴨鍋',          'かもなべ',          'japanese', 'elaborate', 'main', '鴨の火入れと出汁の取り方で仕上がりが変わる'),

-- ============ 洋食 × 簡単 ============
(gen_random_uuid(), 'ナポリタン',     'なぽりたん',        'western', 'easy', 'main', 'ケチャップで炒めた喫茶店風のスパゲッティ'),
(gen_random_uuid(), 'ミートソーススパゲッティ', 'みーとそーすすぱげってぃ', 'western', 'easy', 'main', '挽き肉とトマトのソースを絡めた定番パスタ'),
(gen_random_uuid(), 'オムライス',     'おむらいす',        'western', 'easy', 'main', 'チキンライスを卵で包む。卵の火入れだけ注意'),
(gen_random_uuid(), 'ハンバーグ',     'はんばーぐ',        'western', 'easy', 'main', 'こねて焼くだけ。付け合わせで見栄えが変わる'),
(gen_random_uuid(), 'チキンソテー',   'ちきんそてー',      'western', 'easy', 'main', '皮目をパリッと焼き上げた鶏もも肉'),
(gen_random_uuid(), 'ツナサンド',     'つなさんど',        'western', 'easy', 'main', 'ツナとマヨネーズを挟むだけの手軽な軽食'),
(gen_random_uuid(), 'コーンスープとパン', 'こーんすーぷとぱん', 'western', 'easy', 'soup', '甘みのあるスープとパンで済ませる軽い献立'),
(gen_random_uuid(), 'ベーコンエッグ',  'べーこんえっぐ',     'western', 'easy', 'main', '焼くだけ。朝食にも夜食にも使える'),
(gen_random_uuid(), 'ポテトサラダ',   'ぽてとさらだ',      'western', 'easy', 'side', '茹でて潰して和えるだけ。作り置きにも向く'),
(gen_random_uuid(), 'カルボナーラ',   'かるぼなーら',      'western', 'easy', 'main', '卵とチーズを余熱で和える。分離だけ注意'),
-- ここから 2026-07-22 追加分（洋食 × 簡単を10件→40件）
(gen_random_uuid(), 'ペペロンチーノ',  'ぺぺろんちーの',     'western', 'easy', 'main', 'にんにくと唐辛子だけ。材料が少なく作れる'),
(gen_random_uuid(), 'たらこスパゲッティ', 'たらこすぱげってぃ', 'western', 'easy', 'main', 'ほぐしたたらこを和えるだけ。火を使うのは麺だけ'),
(gen_random_uuid(), 'ジェノベーゼ',   'じぇのべーぜ',      'western', 'easy', 'main', 'バジルの香りを立たせたソースを絡める'),
(gen_random_uuid(), 'ボンゴレビアンコ', 'ぼんごれびあんこ',   'western', 'easy', 'main', 'あさりの出汁で仕上げる。砂抜きだけ前もって'),
(gen_random_uuid(), 'きのこのクリームパスタ', 'きのこのくりーむぱすた', 'western', 'easy', 'main', 'きのこを炒めて生クリームで伸ばす'),
(gen_random_uuid(), 'ミックスサンドイッチ', 'みっくすさんどいっち', 'western', 'easy', 'main', '具を挟んで切るだけ。持ち運びにも向く'),
(gen_random_uuid(), 'ホットサンド',   'ほっとさんど',      'western', 'easy', 'main', '挟んで焼くだけ。中身は残り物でも成立する'),
(gen_random_uuid(), 'ベーコンレタスサンド', 'べーこんれたすさんど', 'western', 'easy', 'main', 'ベーコンを焼いて挟む。野菜も一緒に取れる'),
(gen_random_uuid(), 'フレンチトースト', 'ふれんちとーすと',   'western', 'easy', 'main', '卵液に浸して焼く。前夜に浸しておくと楽'),
(gen_random_uuid(), 'ピザトースト',   'ぴざとーすと',      'western', 'easy', 'main', '食パンに具をのせて焼く。朝食にも軽い夕食にも'),
(gen_random_uuid(), 'チーズトースト',  'ちーずとーすと',     'western', 'easy', 'main', 'のせて焼くだけ。品数が足りない日の一枚'),
(gen_random_uuid(), 'クロックムッシュ', 'くろっくむっしゅ',   'western', 'easy', 'main', 'ハムとチーズを挟んでソースをかけて焼く'),
(gen_random_uuid(), 'オムレツ',      'おむれつ',          'western', 'easy', 'main', '卵3個で作れる。形を整えるのは慣れ次第'),
(gen_random_uuid(), 'スパニッシュオムレツ', 'すぱにっしゅおむれつ', 'western', 'easy', 'main', 'じゃがいもを入れて厚く焼く。冷めても旨い'),
(gen_random_uuid(), 'ジャーマンポテト', 'じゃーまんぽてと',   'western', 'easy', 'side', 'じゃがいもとベーコンを炒めるだけ'),
(gen_random_uuid(), 'ポークソテー',   'ぽーくそてー',      'western', 'easy', 'main', '筋を切って焼くだけ。厚切りでも失敗が少ない'),
(gen_random_uuid(), 'ステーキ',      'すてーき',          'western', 'easy', 'main', '焼くだけだが、休ませる時間で仕上がりが変わる'),
(gen_random_uuid(), 'ハンバーガー',   'はんばーがー',      'western', 'easy', 'main', 'パティを焼いて挟む。好きな具を足せる'),
(gen_random_uuid(), 'ミートボールのトマト煮', 'みーとぼーるのとまとに', 'western', 'easy', 'main', '丸めて煮るだけ。多めに作って翌日にも回せる'),
(gen_random_uuid(), 'ドリア',        'どりあ',            'western', 'easy', 'main', 'ご飯にソースをかけて焼く。余りご飯の使い道に'),
(gen_random_uuid(), 'ピラフ',        'ぴらふ',            'western', 'easy', 'main', '具材と米を炒めて炊く。一皿で完結する'),
(gen_random_uuid(), 'シーザーサラダ',  'しーざーさらだ',     'western', 'easy', 'side', 'レタスにドレッシングとチーズを絡める'),
(gen_random_uuid(), 'コブサラダ',     'こぶさらだ',        'western', 'easy', 'main', '具を角切りにして並べる。これだけで主菜になる'),
(gen_random_uuid(), 'カプレーゼ',     'かぷれーぜ',        'western', 'easy', 'side', '切って並べるだけ。トマトの質がそのまま出る'),
(gen_random_uuid(), 'ニース風サラダ',  'にーすふうさらだ',    'western', 'easy', 'side', 'ツナと卵を合わせた食べ応えのあるサラダ'),
(gen_random_uuid(), 'マカロニサラダ',  'まかろにさらだ',     'western', 'easy', 'side', '茹でて和えるだけ。作り置きにも向く'),
(gen_random_uuid(), 'クラムチャウダー', 'くらむちゃうだー',   'western', 'easy', 'soup', 'あさりの缶詰を使えば短時間で仕上がる'),
(gen_random_uuid(), 'かぼちゃのポタージュ', 'かぼちゃのぽたーじゅ', 'western', 'easy', 'soup', '煮て潰して伸ばすだけ。甘みで子どもも食べやすい'),
(gen_random_uuid(), 'ポークビーンズ',  'ぽーくびーんず',     'western', 'easy', 'main', '豆と豚肉をトマトで煮る。水煮豆を使えば早い'),
(gen_random_uuid(), 'アヒージョ',     'あひーじょ',        'western', 'easy', 'main', 'にんにくと油で煮るだけ。残った油はパンに'),

-- ============ 洋食 × 普通 ============
(gen_random_uuid(), 'ロールキャベツ',  'ろーるきゃべつ',     'western', 'normal', 'main', 'キャベツで挽き肉を巻き、スープで煮込む'),
(gen_random_uuid(), 'グラタン',      'ぐらたん',          'western', 'normal', 'main', 'ホワイトソースを作ってオーブンで焼き上げる'),
(gen_random_uuid(), 'ミネストローネ',  'みねすとろーね',     'western', 'normal', 'soup', '野菜を細かく切り揃えて煮込むトマトのスープ'),
(gen_random_uuid(), 'ポトフ',        'ぽとふ',            'western', 'normal', 'main', '大ぶりの野菜と肉をじっくり煮込む'),
(gen_random_uuid(), 'チキンのトマト煮込み', 'ちきんのとまとにこみ', 'western', 'normal', 'main', '鶏肉をトマトとハーブで煮込んだ一皿'),
(gen_random_uuid(), 'キッシュ',      'きっしゅ',          'western', 'normal', 'main', '生地を敷いて卵液を流し、オーブンで焼く'),
(gen_random_uuid(), 'ハヤシライス',   'はやしらいす',      'western', 'normal', 'main', 'デミグラス風のソースで牛肉と玉ねぎを煮る'),
(gen_random_uuid(), 'クリームシチュー', 'くりーむしちゅー',   'western', 'normal', 'main', 'ルウから作ると小麦粉の炒め加減が味を決める'),
(gen_random_uuid(), 'アクアパッツァ',  'あくあぱっつぁ',     'western', 'normal', 'main', '白身魚とあさりを蒸し煮にした地中海風'),
(gen_random_uuid(), 'ガーリックシュリンプ', 'がーりっくしゅりんぷ', 'western', 'normal', 'main', 'にんにくとバターで海老を焼き付ける'),
-- ここから 2026-07-22 追加分（洋食 × 普通を10件→40件）
(gen_random_uuid(), 'ビーフストロガノフ', 'びーふすとろがのふ',  'western', 'normal', 'main', '牛肉ときのこをサワークリームで煮る'),
(gen_random_uuid(), 'ミートローフ',   'みーとろーふ',      'western', 'normal', 'main', '型に詰めて焼く。切り口に卵を覗かせると見栄えする'),
(gen_random_uuid(), 'ローストチキン',  'ろーすとちきん',     'western', 'normal', 'main', '下味を付けてオーブンに任せる。焼き時間は長め'),
(gen_random_uuid(), 'ローストポーク',  'ろーすとぽーく',     'western', 'normal', 'main', '塊肉を焼いて休ませる。薄く切って盛り付ける'),
(gen_random_uuid(), 'スペアリブのオーブン焼き', 'すぺありぶのおーぶんやき', 'western', 'normal', 'main', '漬け込んでから焼く。骨付き肉の食べ応えがある'),
(gen_random_uuid(), 'チキンのハーブ焼き', 'ちきんのはーぶやき',  'western', 'normal', 'main', 'ハーブと野菜を天板に並べて一緒に焼く'),
(gen_random_uuid(), 'サルティンボッカ', 'さるてぃんぼっか',   'western', 'normal', 'main', '生ハムを重ねて焼くローマの料理。塩気は生ハム任せ'),
(gen_random_uuid(), 'コロッケ',      'ころっけ',          'western', 'normal', 'main', '潰して丸めて揚げる。工程は多いが難しくはない'),
(gen_random_uuid(), 'メンチカツ',     'めんちかつ',        'western', 'normal', 'main', '肉だねの水分を閉じ込めるのがコツ'),
(gen_random_uuid(), 'クリームコロッケ', 'くりーむころっけ',   'western', 'normal', 'main', 'ホワイトソースを冷やし固めてから成形する'),
(gen_random_uuid(), 'エビフライ',     'えびふらい',        'western', 'normal', 'main', '背わたを取り、まっすぐ伸ばしてから揚げる'),
(gen_random_uuid(), 'ミラノ風カツレツ', 'みらのふうかつれつ',  'western', 'normal', 'main', '薄く叩いた肉に粉チーズ入りの衣を付けて焼く'),
(gen_random_uuid(), 'フィッシュアンドチップス', 'ふぃっしゅあんどちっぷす', 'western', 'normal', 'main', '白身魚と芋を揚げる。衣をふわりとさせるのが要'),
(gen_random_uuid(), 'ポークチャップ',  'ぽーくちゃっぷ',     'western', 'normal', 'main', '焼いた豚肉をケチャップソースで絡める洋食屋の味'),
(gen_random_uuid(), 'グーラッシュ',   'ぐーらっしゅ',      'western', 'normal', 'main', 'パプリカを効かせて牛肉を煮込むハンガリー料理'),
(gen_random_uuid(), 'チリコンカン',   'ちりこんかん',      'western', 'normal', 'main', '豆と挽き肉をスパイスで煮込む。パンにもご飯にも'),
(gen_random_uuid(), 'シェパーズパイ',  'しぇぱーずぱい',     'western', 'normal', 'main', '挽き肉の上にマッシュポテトを重ねて焼く'),
(gen_random_uuid(), 'ミートパイ',     'みーとぱい',        'western', 'normal', 'main', '市販の生地を使えば手が届く。具は前日に作れる'),
(gen_random_uuid(), 'ジャンバラヤ',   'じゃんばらや',      'western', 'normal', 'main', 'スパイスを効かせて米ごと炊き込むアメリカ南部の料理'),
(gen_random_uuid(), 'リゾット',      'りぞっと',          'western', 'normal', 'main', '出汁を少しずつ加えて米に吸わせる。芯の残し加減が要'),
(gen_random_uuid(), 'ニョッキ',      'にょっき',          'western', 'normal', 'main', 'じゃがいもの生地を丸めて茹でる。成形に手間がかかる'),
(gen_random_uuid(), 'ペスカトーレ',   'ぺすかとーれ',      'western', 'normal', 'main', '複数の魚介の出汁をトマトソースに移す'),
(gen_random_uuid(), 'アラビアータ',   'あらびあーた',      'western', 'normal', 'main', '唐辛子を効かせたトマトソース。辛さの加減が要'),
(gen_random_uuid(), '白身魚のムニエル', 'しろみざかなのむにえる', 'western', 'normal', 'main', '粉をはたいてバターで焼く。焦がしバターで香りを出す'),
(gen_random_uuid(), 'サーモンのクリーム煮', 'さーもんのくりーむに', 'western', 'normal', 'main', '崩れやすい身を扱いながら生クリームで煮る'),
(gen_random_uuid(), 'ムール貝の白ワイン蒸し', 'むーるがいのしろわいんむし', 'western', 'normal', 'main', '貝の掃除さえ済めば蒸すだけ。残った汁も使える'),
(gen_random_uuid(), 'ラタトゥイユ',   'らたとぅいゆ',      'western', 'normal', 'side', '夏野菜を別々に炒めてから煮合わせる'),
(gen_random_uuid(), 'オニオングラタンスープ', 'おにおんぐらたんすーぷ', 'western', 'normal', 'soup', '玉ねぎを飴色になるまで炒める。ここに時間がかかる'),
(gen_random_uuid(), 'ヴィシソワーズ',  'びしそわーず',      'western', 'normal', 'soup', 'じゃがいもの冷製スープ。裏ごしの丁寧さが出る'),
(gen_random_uuid(), 'エッグベネディクト', 'えっぐべねでぃくと', 'western', 'normal', 'main', 'ポーチドエッグとソースを同時に仕上げる段取りが要る'),

-- ============ 洋食 × 手が込んだ ============
(gen_random_uuid(), 'ビーフシチュー',  'びーふしちゅー',     'western', 'elaborate', 'main', '牛肉を数時間煮込む。赤ワインで香りを重ねる'),
(gen_random_uuid(), 'ラザニア',      'らざにあ',          'western', 'elaborate', 'main', 'ミートソースとベシャメルを層に重ねて焼く'),
(gen_random_uuid(), 'ローストビーフ',  'ろーすとびーふ',     'western', 'elaborate', 'main', '低温でじっくり火入れし、休ませて仕上げる'),
(gen_random_uuid(), 'ブイヤベース',   'ぶいやべーす',      'western', 'elaborate', 'main', '複数の魚介から出汁を取る南仏の魚介鍋'),
(gen_random_uuid(), 'パエリア',      'ぱえりあ',          'western', 'elaborate', 'main', '米に出汁を吸わせ、おこげまで作る'),
(gen_random_uuid(), 'コンフィ・ド・カナール', 'こんふぃどかなーる', 'western', 'elaborate', 'main', '鴨を脂で低温調理する保存食由来の一品'),
(gen_random_uuid(), 'ビーフウェリントン', 'びーふうぇりんとん', 'western', 'elaborate', 'main', 'フィレ肉をパイ生地で包んで焼く。火入れが難所'),
(gen_random_uuid(), 'オッソブーコ',   'おっそぶーこ',      'western', 'elaborate', 'main', '仔牛のすね肉を白ワインで煮込むミラノ料理'),
(gen_random_uuid(), 'テリーヌ',      'てりーぬ',          'western', 'elaborate', 'main', '型に詰めて湯煎焼きし、冷やして仕上げる'),
(gen_random_uuid(), 'コック・オ・ヴァン', 'こっくおゔぁん',    'western', 'elaborate', 'main', '鶏を赤ワインで煮込むフランスの郷土料理'),

-- ============ 中華 × 簡単 ============
(gen_random_uuid(), '麻婆豆腐',      'まーぼーどうふ',     'chinese', 'easy', 'main', '豆板醤と豆腐で作る、短時間で仕上がる定番'),
(gen_random_uuid(), 'チャーハン',     'ちゃーはん',        'chinese', 'easy', 'main', '強火で手早く炒める。冷やご飯の活用にも'),
(gen_random_uuid(), '回鍋肉',        'ほいこーろー',      'chinese', 'easy', 'main', 'キャベツと豚肉を甜麺醤で炒める'),
(gen_random_uuid(), '青椒肉絲',      'ちんじゃおろーす',   'chinese', 'easy', 'main', 'ピーマンと細切り肉を手早く炒める'),
(gen_random_uuid(), '中華スープ',     'ちゅうかすーぷ',     'chinese', 'easy', 'soup', '鶏がらベースの卵スープ。副菜としても'),
(gen_random_uuid(), '冷やし中華',     'ひやしちゅうか',     'chinese', 'easy', 'main', '具材を千切りにして並べる。夏の定番'),
(gen_random_uuid(), '卵とトマトの炒め物', 'たまごととまとのいためもの', 'chinese', 'easy', 'main', '卵をふんわり仕上げるのがコツ'),
(gen_random_uuid(), '焼きビーフン',   'やきびーふん',      'chinese', 'easy', 'main', '戻した米麺と野菜を炒め合わせる'),
(gen_random_uuid(), 'ニラ玉',        'にらたま',          'chinese', 'easy', 'main', 'ニラと卵を炒めるだけ。手早く一品追加できる'),
(gen_random_uuid(), '天津飯',        'てんしんはん',      'chinese', 'easy', 'main', 'かに玉をご飯にのせ、あんをかける'),
-- ここから 2026-07-22 追加分（中華 × 簡単を10件→40件）
(gen_random_uuid(), '醤油ラーメン',   'しょうゆらーめん',    'chinese', 'easy', 'main', '市販のスープを使えば具を用意するだけ'),
(gen_random_uuid(), '味噌ラーメン',   'みそらーめん',      'chinese', 'easy', 'main', '炒めた野菜をのせると一杯で満足できる'),
(gen_random_uuid(), 'タンメン',      'たんめん',          'chinese', 'easy', 'main', '野菜をたっぷり煮た塩味の麺。野菜の消費に向く'),
(gen_random_uuid(), '焼きそば',      'やきそば',          'chinese', 'easy', 'main', '麺と野菜を炒めるだけ。冷蔵庫の整理にも'),
(gen_random_uuid(), 'あんかけ焼きそば', 'あんかけやきそば',   'chinese', 'easy', 'main', '焼いた麺に具だくさんのあんをかける'),
(gen_random_uuid(), '油そば',        'あぶらそば',        'chinese', 'easy', 'main', 'スープを作らない分だけ手間が少ない'),
(gen_random_uuid(), 'ジャージャー麺',  'じゃーじゃーめん',    'chinese', 'easy', 'main', '肉味噌を作って麺にのせる。作り置きが効く'),
(gen_random_uuid(), 'マーボー春雨',   'まーぼーはるさめ',    'chinese', 'easy', 'main', '春雨が汁を吸うので少ない材料で満足感が出る'),
(gen_random_uuid(), '中華粥',        'ちゅうかがゆ',      'chinese', 'easy', 'main', '米から煮るだけ。体調が優れない日にも'),
(gen_random_uuid(), 'ネギチャーシュー丼', 'ねぎちゃーしゅーどん', 'chinese', 'easy', 'main', '市販のチャーシューとねぎをご飯にのせる'),
(gen_random_uuid(), 'かに玉',        'かにたま',          'chinese', 'easy', 'main', 'ふんわり焼いてあんをかける。具は缶詰でも'),
(gen_random_uuid(), 'えびマヨ',      'えびまよ',          'chinese', 'easy', 'main', '揚げた海老をソースで和える。市販の惣菜より軽く作れる'),
(gen_random_uuid(), 'ニラレバ炒め',   'にらればいため',     'chinese', 'easy', 'main', 'レバーの下処理さえ済めば炒めるだけ'),
(gen_random_uuid(), 'もやしと豚肉の炒め物', 'もやしとぶたにくのいためもの', 'chinese', 'easy', 'main', '材料が安く、5分で仕上がる'),
(gen_random_uuid(), '豆苗と豚肉の炒め物', 'とうみょうとぶたにくのいためもの', 'chinese', 'easy', 'main', 'シャキッとした食感を残すよう手早く炒める'),
(gen_random_uuid(), 'チンゲン菜と海老の炒め物', 'ちんげんさいとえびのいためもの', 'chinese', 'easy', 'main', '色よく仕上げるため強火で短時間に'),
(gen_random_uuid(), '鶏肉とカシューナッツの炒め物', 'とりにくとかしゅーなっつのいためもの', 'chinese', 'easy', 'main', 'ナッツの食感が加わる。冷めても食べやすい'),
(gen_random_uuid(), '肉団子の甘酢あん', 'にくだんごのあまずあん', 'chinese', 'easy', 'main', '丸めて揚げて絡めるだけ。多めに作れる'),
(gen_random_uuid(), '鶏むね肉の中華蒸し', 'とりむねにくのちゅうかむし', 'chinese', 'easy', 'main', '蒸すだけで柔らかい。たれを変えれば飽きない'),
(gen_random_uuid(), '豚バラと白菜の重ね蒸し', 'ぶたばらとはくさいのかさねむし', 'chinese', 'easy', 'main', '重ねて蒸すだけ。白菜が多い時期に'),
(gen_random_uuid(), '手羽先の甘辛煮',  'てばさきのあまからに', 'chinese', 'easy', 'main', '煮汁に入れて放っておける。骨からの出汁が効く'),
(gen_random_uuid(), '中華風あんかけ豆腐', 'ちゅうかふうあんかけどうふ', 'chinese', 'easy', 'main', '豆腐を温めてあんをかけるだけ'),
(gen_random_uuid(), 'バンバンジー',   'ばんばんじー',      'chinese', 'easy', 'side', '茹で鶏ときゅうりにごまだれをかける'),
(gen_random_uuid(), '春雨サラダ',     'はるさめさらだ',     'chinese', 'easy', 'side', '戻して和えるだけ。もう一品欲しい日に'),
(gen_random_uuid(), 'きゅうりの中華和え', 'きゅうりのちゅうかあえ', 'chinese', 'easy', 'side', '叩いて和えるだけ。箸休めになる'),
(gen_random_uuid(), '水餃子',        'すいぎょうざ',      'chinese', 'easy', 'main', '茹でるので焼き加減を気にしなくてよい'),
(gen_random_uuid(), 'ワンタンスープ',  'わんたんすーぷ',     'chinese', 'easy', 'soup', '包む手間はあるが、具は少なくて済む'),
(gen_random_uuid(), 'わかめスープ',   'わかめすーぷ',      'chinese', 'easy', 'soup', '数分でできる。主菜が重い日に合わせやすい'),
(gen_random_uuid(), 'サンラータン',   'さんらーたん',      'chinese', 'easy', 'soup', '酸味と辛味を後から足して調整できる'),
(gen_random_uuid(), '中華コーンスープ', 'ちゅうかこーんすーぷ', 'chinese', 'easy', 'soup', '缶詰と卵で作れる。子どもも食べやすい'),

-- ============ 中華 × 普通 ============
(gen_random_uuid(), '餃子',          'ぎょうざ',          'chinese', 'normal', 'main', '包む手間はあるが、焼き加減で差が出る'),
(gen_random_uuid(), '酢豚',          'すぶた',            'chinese', 'normal', 'main', '揚げた豚肉に甘酢あんを絡める'),
(gen_random_uuid(), 'エビチリ',      'えびちり',          'chinese', 'normal', 'main', '海老の下処理とチリソースの辛さ調整がポイント'),
(gen_random_uuid(), '春巻き',        'はるまき',          'chinese', 'normal', 'main', '具を炒めて冷まし、包んで揚げる'),
(gen_random_uuid(), '担々麺',        'たんたんめん',      'chinese', 'normal', 'main', '芝麻醤のスープと肉味噌を合わせる'),
(gen_random_uuid(), '油淋鶏',        'ゆーりんちー',      'chinese', 'normal', 'main', '揚げた鶏に葱ダレをかける'),
(gen_random_uuid(), '八宝菜',        'はっぽうさい',      'chinese', 'normal', 'main', '多種の具材を炒めてあんでまとめる'),
(gen_random_uuid(), '麻婆茄子',      'まーぼーなす',      'chinese', 'normal', 'main', '茄子を素揚げしてから炒め合わせる'),
(gen_random_uuid(), '焼売',          'しゅうまい',        'chinese', 'normal', 'main', '餡を包んで蒸す。皮の扱いに慣れが要る'),
(gen_random_uuid(), '中華丼',        'ちゅうかどん',      'chinese', 'normal', 'main', '八宝菜風の具をご飯にのせる'),
-- ここから 2026-07-22 追加分（中華 × 普通を10件→40件）
(gen_random_uuid(), 'よだれ鶏',      'よだれどり',        'chinese', 'normal', 'main', '茹で鶏に香味だれをかける。たれの配合が味を決める'),
(gen_random_uuid(), '白身魚の中華蒸し', 'しろみざかなのちゅうかむし', 'chinese', 'normal', 'main', '蒸し上がりに熱した油をかけて香りを立たせる'),
(gen_random_uuid(), 'えびとブロッコリーの炒め物', 'えびとぶろっこりーのいためもの', 'chinese', 'normal', 'main', '海老の下処理と火の入れ具合で食感が変わる'),
(gen_random_uuid(), 'いかと野菜の中華炒め', 'いかとやさいのちゅうかいため', 'chinese', 'normal', 'main', 'いかは火を通しすぎると硬くなるので手早く'),
(gen_random_uuid(), '牛肉のオイスターソース炒め', 'ぎゅうにくのおいすたーそーすいため', 'chinese', 'normal', 'main', '下味と片栗粉で肉を柔らかく保つ'),
(gen_random_uuid(), '牛肉とセロリの炒め物', 'ぎゅうにくとせろりのいためもの', 'chinese', 'normal', 'main', 'セロリの香りを残すため最後に合わせる'),
(gen_random_uuid(), 'えびと卵の炒め物', 'えびとたまごのいためもの', 'chinese', 'normal', 'main', '卵を半熟で取り出し、最後に戻すのがコツ'),
(gen_random_uuid(), '鶏肉のねぎ塩炒め', 'とりにくのねぎしおいため', 'chinese', 'normal', 'main', 'ねぎをたっぷり使い、塩味で素材を立たせる'),
(gen_random_uuid(), 'にんにくの芽と豚肉の炒め物', 'にんにくのめとぶたにくのいためもの', 'chinese', 'normal', 'main', '香りが強く、ご飯が進む。下茹でで食感を整える'),
(gen_random_uuid(), 'ザーサイと豚肉の炒め物', 'ざーさいとぶたにくのいためもの', 'chinese', 'normal', 'main', '搾菜の塩気を活かすので味付けは控えめに'),
(gen_random_uuid(), '空芯菜炒め',     'くうしんさいいため',  'chinese', 'normal', 'side', '強火で一気に炒めて茎の食感を残す'),
(gen_random_uuid(), '揚げ茄子の香味だれ', 'あげなすのこうみだれ', 'chinese', 'normal', 'side', '素揚げした茄子に香味だれを絡める'),
(gen_random_uuid(), '中華風スペアリブ', 'ちゅうかふうすぺありぶ', 'chinese', 'normal', 'main', '揚げてから甘酢あんを絡める。骨付きで食べ応えがある'),
(gen_random_uuid(), '豚バラと厚揚げの中華煮', 'ぶたばらとあつあげのちゅうかに', 'chinese', 'normal', 'main', '厚揚げが煮汁を吸う。時間をかけるほど味が入る'),
(gen_random_uuid(), '白菜と肉団子の煮込み', 'はくさいとにくだんごのにこみ', 'chinese', 'normal', 'main', '肉団子から出た旨味を白菜に含ませる'),
(gen_random_uuid(), 'えびの蒸し餃子',  'えびのむしぎょうざ',  'chinese', 'normal', 'main', '海老を粗く刻んで食感を残す。包み方に慣れが要る'),
(gen_random_uuid(), 'ニラ饅頭',      'にらまんじゅう',     'chinese', 'normal', 'main', 'ニラをたっぷり包んで焼く。皮は市販でも作れる'),
(gen_random_uuid(), '揚げワンタン',   'あげわんたん',      'chinese', 'normal', 'main', '包んで揚げるだけだが、数を作るのに時間がかかる'),
(gen_random_uuid(), '肉まん',        'にくまん',          'chinese', 'normal', 'main', '生地を発酵させて包む。蒸し上がりの見極めが要る'),
(gen_random_uuid(), '大根餅',        'だいこんもち',      'chinese', 'normal', 'side', 'すりおろした大根を蒸してから焼く。工程が二段階'),
(gen_random_uuid(), '中華おこわ',     'ちゅうかおこわ',     'chinese', 'normal', 'main', 'もち米を蒸して具と合わせる。水加減が難しい'),
(gen_random_uuid(), 'くらげの冷菜',   'くらげのれいさい',    'chinese', 'normal', 'side', '塩抜きと戻しに時間がかかるが、和えるだけ'),
(gen_random_uuid(), '酸辣湯麺',      'さんらーたんめん',    'chinese', 'normal', 'main', '具材を細切りに揃える手間がかかる'),
(gen_random_uuid(), 'パーコー麺',     'ぱーこーめん',      'chinese', 'normal', 'main', '揚げた豚肉を麺にのせる。揚げ物と麺を同時に仕上げる'),
(gen_random_uuid(), '牛肉麺',        'ぎゅうにくめん',     'chinese', 'normal', 'main', '牛すね肉を煮込んでスープごと麺に合わせる'),
(gen_random_uuid(), '台湾まぜそば',   'たいわんまぜそば',    'chinese', 'normal', 'main', '具を別々に仕込んで麺にのせ、混ぜて食べる'),
(gen_random_uuid(), 'ちゃんぽん',     'ちゃんぽん',        'chinese', 'normal', 'main', '具材が多く、切り物に時間がかかる'),
(gen_random_uuid(), '皿うどん',      'さらうどん',        'chinese', 'normal', 'main', '揚げ麺に熱いあんをかける。あんの濃度が要'),
(gen_random_uuid(), 'ルーロー飯',     'るーろーはん',      'chinese', 'normal', 'main', '豚バラを甘辛く煮込んでご飯にかける台湾の定番'),
(gen_random_uuid(), 'トマトと卵のスープ', 'とまととたまごのすーぷ', 'chinese', 'normal', 'soup', '卵を細く流し入れて筋を作る'),

-- ============ 中華 × 手が込んだ ============
(gen_random_uuid(), '北京ダック',     'ぺきんだっく',      'chinese', 'elaborate', 'main', '皮をパリッと焼き上げる。仕込みに数日かかる'),
(gen_random_uuid(), '小籠包',        'しょうろんぽう',     'chinese', 'elaborate', 'main', 'スープを煮凝りにして包む。皮も手作り'),
(gen_random_uuid(), 'フカヒレの姿煮',  'ふかひれのすがたに',  'chinese', 'elaborate', 'main', '戻しと煮込みに時間をかける高級料理'),
(gen_random_uuid(), '東坡肉',        'とんぽーろー',      'chinese', 'elaborate', 'main', '豚バラを長時間煮込んでとろとろに仕上げる'),
(gen_random_uuid(), '佛跳牆',        'ぶっちょうしょう',   'chinese', 'elaborate', 'main', '多数の高級食材を壺で蒸し込む福建料理'),
(gen_random_uuid(), '上海蟹の紹興酒漬け', 'しゃんはいがにのしょうこうしゅづけ', 'chinese', 'elaborate', 'main', '生の蟹を紹興酒に漬け込む。仕込みに数日'),
(gen_random_uuid(), '中華ちまき',     'ちゅうかちまき',     'chinese', 'elaborate', 'main', 'もち米と具材を竹皮で包んで蒸す'),
(gen_random_uuid(), '刀削麺',        'とうしょうめん',     'chinese', 'elaborate', 'main', '生地を削って茹でる。麺打ちの技術が要る'),
(gen_random_uuid(), '火鍋',          'ひなべ',            'chinese', 'elaborate', 'main', '複数のスープと薬味を揃える。準備が大がかり'),
(gen_random_uuid(), '叉焼',          'ちゃーしゅー',      'chinese', 'elaborate', 'main', '漬け込みと焼きに時間をかける'),

-- ============ その他 × 簡単 ============
(gen_random_uuid(), 'カレーライス',   'かれーらいす',      'other', 'easy', 'main', 'ルウを使えば失敗が少ない。作り置きにも向く'),
(gen_random_uuid(), 'タコライス',     'たこらいす',        'other', 'easy', 'main', '挽き肉と野菜をご飯にのせる沖縄発の一皿'),
(gen_random_uuid(), 'ガパオライス',   'がぱおらいす',      'other', 'easy', 'main', 'バジルと挽き肉を炒めて目玉焼きをのせる'),
(gen_random_uuid(), 'ビビンバ',      'びびんば',          'other', 'easy', 'main', 'ナムルと肉をご飯にのせて混ぜる'),
(gen_random_uuid(), 'キムチチゲ',     'きむちちげ',        'other', 'easy', 'main', 'キムチと豆腐を煮るだけ。体が温まる'),
(gen_random_uuid(), 'チキンオーバーライス', 'ちきんおーばーらいす', 'other', 'easy', 'main', 'スパイスチキンとサラダをご飯にのせる'),
(gen_random_uuid(), 'サラダボウル',   'さらだぼうる',      'other', 'easy', 'side', '野菜とタンパク質を一皿に。軽く済ませたい日に'),
(gen_random_uuid(), 'ホットドッグ',   'ほっとどっぐ',      'other', 'easy', 'main', 'ソーセージを挟むだけ。手軽な軽食'),
(gen_random_uuid(), 'タコス',        'たこす',            'other', 'easy', 'main', '具材を用意して各自で巻く'),
(gen_random_uuid(), 'プルコギ',      'ぷるこぎ',          'other', 'easy', 'main', '甘辛いタレで牛肉と野菜を炒める'),
-- ここから 2026-07-22 追加分（その他 × 簡単を10件→40件）
(gen_random_uuid(), '豚キムチ',      'ぶたきむち',        'other', 'easy', 'main', 'キムチと豚肉を炒めるだけ。味付けはキムチ任せ'),
(gen_random_uuid(), 'チヂミ',        'ちぢみ',            'other', 'easy', 'main', '生地に具を混ぜて焼く。カリッと焼くのがコツ'),
(gen_random_uuid(), 'キンパ',        'きんぱ',            'other', 'easy', 'main', '具を並べて巻く韓国風のり巻き。作り置きにも'),
(gen_random_uuid(), 'ヤンニョムチキン', 'やんにょむちきん',   'other', 'easy', 'main', '揚げた鶏に甘辛いタレを絡める'),
(gen_random_uuid(), 'チーズタッカルビ', 'ちーずたっかるび',   'other', 'easy', 'main', '鶏と野菜を炒めてチーズを絡める。一皿で完結する'),
(gen_random_uuid(), 'ビビン麺',      'びびんめん',        'other', 'easy', 'main', '茹でた麺に辛いタレを和える。暑い日に'),
(gen_random_uuid(), 'トッポギ',      'とっぽぎ',          'other', 'easy', 'main', '餅を甘辛く煮るだけ。小腹にも主食にも'),
(gen_random_uuid(), 'テンジャンチゲ',  'てんじゃんちげ',     'other', 'easy', 'main', '韓国味噌で野菜と豆腐を煮る素朴な鍋'),
(gen_random_uuid(), 'プデチゲ',      'ぷでちげ',          'other', 'easy', 'main', 'ソーセージやハムを入れて煮る。冷蔵庫の余り物が使える'),
(gen_random_uuid(), 'スープカレー',   'すーぷかれー',      'other', 'easy', 'main', '具材を大きめに切って煮る。ルウを使えば手軽'),
(gen_random_uuid(), 'ドライカレー',   'どらいかれー',      'other', 'easy', 'main', '汁気を飛ばして炒める。弁当にも回せる'),
(gen_random_uuid(), 'キーマカレー',   'きーまかれー',      'other', 'easy', 'main', '挽き肉なので煮込み時間が短くて済む'),
(gen_random_uuid(), 'カレーうどん',   'かれーうどん',      'other', 'easy', 'main', '前日のカレーを出汁で伸ばせば作り直しが要らない'),
(gen_random_uuid(), 'タンドリーチキン', 'たんどりーちきん',   'other', 'easy', 'main', 'ヨーグルトとスパイスに漬けて焼くだけ'),
(gen_random_uuid(), 'ロコモコ',      'ろこもこ',          'other', 'easy', 'main', 'ハンバーグと目玉焼きをご飯にのせる'),
(gen_random_uuid(), 'ポキ丼',        'ぽきどん',          'other', 'easy', 'main', '刺身を漬けてご飯にのせる。火を使わない'),
(gen_random_uuid(), 'スパムおにぎり',  'すぱむおにぎり',     'other', 'easy', 'main', '焼いたスパムと卵を挟む。持ち運びやすい'),
(gen_random_uuid(), 'ガーリックライス', 'がーりっくらいす',   'other', 'easy', 'main', '炒めるだけ。肉料理の付け合わせにもなる'),
(gen_random_uuid(), 'パッタイ',      'ぱったい',          'other', 'easy', 'main', '米麺を戻して炒める。甘酸っぱさが特徴'),
(gen_random_uuid(), 'ミーゴレン',     'みーごれん',        'other', 'easy', 'main', '甘辛く炒めるインドネシア風の焼きそば'),
(gen_random_uuid(), 'カオマンガイ',   'かおまんがい',      'other', 'easy', 'main', '鶏を茹でて、その汁で米を炊く。鍋一つで済む'),
(gen_random_uuid(), '生春巻き',      'なまはるまき',      'other', 'easy', 'side', '巻くだけで火を使わない。具は残り物でも'),
(gen_random_uuid(), 'バインミー',     'ばいんみー',        'other', 'easy', 'main', 'バゲットに肉と香草を挟むベトナムのサンドイッチ'),
(gen_random_uuid(), 'ソムタム',      'そむたむ',          'other', 'easy', 'side', '青パパイヤを和えるタイのサラダ。辛さは好みで'),
(gen_random_uuid(), 'ヤムウンセン',   'やむうんせん',      'other', 'easy', 'side', '春雨と海老を和えるだけ。作り置きが効く'),
(gen_random_uuid(), 'ケサディーヤ',   'けさでぃーや',      'other', 'easy', 'main', 'チーズを挟んで焼くだけ。子どもも食べやすい'),
(gen_random_uuid(), 'ブリトー',      'ぶりとー',          'other', 'easy', 'main', '具を包むだけ。片手で食べられる'),
(gen_random_uuid(), 'ラップサンド',   'らっぷさんど',      'other', 'easy', 'main', '野菜と肉を巻く。朝食にも弁当にも'),
(gen_random_uuid(), 'ピタサンド',     'ぴたさんど',        'other', 'easy', 'main', 'ピタパンを開いて詰めるだけ'),
(gen_random_uuid(), 'シャクシュカ',   'しゃくしゅか',      'other', 'easy', 'main', 'トマトソースに卵を落とすだけ。フライパン一つで'),

-- ============ その他 × 普通 ============
(gen_random_uuid(), 'トムヤムクン',   'とむやむくん',      'other', 'normal', 'soup', '酸味と辛味のバランスを取るタイの海老スープ'),
(gen_random_uuid(), 'グリーンカレー',  'ぐりーんかれー',     'other', 'normal', 'main', 'ペーストとココナッツミルクで作るタイカレー'),
(gen_random_uuid(), 'チャプチェ',     'ちゃぷちぇ',        'other', 'normal', 'main', '春雨と野菜を炒め合わせた韓国料理'),
(gen_random_uuid(), 'スンドゥブチゲ',  'すんどぅぶちげ',     'other', 'normal', 'main', '純豆腐を使った辛味のある鍋'),
(gen_random_uuid(), 'バターチキンカレー', 'ばたーちきんかれー', 'other', 'normal', 'main', 'トマトとバターでまろやかに仕上げるインドカレー'),
(gen_random_uuid(), 'フォー',        'ふぉー',            'other', 'normal', 'main', '澄んだスープと米麺のベトナム料理'),
(gen_random_uuid(), 'ケバブプレート',  'けばぶぷれーと',     'other', 'normal', 'main', 'スパイスで漬けた肉を焼いてライスと合わせる'),
(gen_random_uuid(), 'チキンティッカマサラ', 'ちきんてぃっかまさら', 'other', 'normal', 'main', '焼いた鶏をスパイスソースで煮込む'),
(gen_random_uuid(), 'サムギョプサル',  'さむぎょぷさる',     'other', 'normal', 'main', '豚バラを焼いて野菜で包む'),
(gen_random_uuid(), 'ナシゴレン',     'なしごれん',        'other', 'normal', 'main', 'ケチャップマニスで炒めるインドネシア風炒飯'),
-- ここから 2026-07-22 追加分（その他 × 普通を10件→40件）
(gen_random_uuid(), 'カルビチム',     'かるびちむ',        'other', 'normal', 'main', '牛肉と根菜を甘辛く煮込む韓国の祝い料理'),
(gen_random_uuid(), 'タッカンマリ',   'たっかんまり',      'other', 'normal', 'main', '鶏を丸ごと煮て、たれを付けて食べる。締めは麺で'),
(gen_random_uuid(), 'ユッケジャン',   'ゆっけじゃん',      'other', 'normal', 'main', '牛肉とぜんまいを煮込む辛いスープ。具を裂く手間がある'),
(gen_random_uuid(), 'コムタン',      'こむたん',          'other', 'normal', 'main', '牛の骨と肉を長時間煮出した白いスープ'),
(gen_random_uuid(), 'ポッサム',      'ぽっさむ',          'other', 'normal', 'main', '茹でた豚バラを野菜で包む。茹で加減が要'),
(gen_random_uuid(), 'カムジャタン',   'かむじゃたん',      'other', 'normal', 'main', 'じゃがいもと豚肉を煮込む韓国の鍋'),
(gen_random_uuid(), 'タットリタン',   'たっとりたん',      'other', 'normal', 'main', '鶏とじゃがいもを辛く煮る。日本の肉じゃがに近い作り方'),
(gen_random_uuid(), 'カオソーイ',     'かおそーい',        'other', 'normal', 'main', '揚げ麺と煮麺を合わせるタイ北部のカレー麺'),
(gen_random_uuid(), 'ラクサ',        'らくさ',            'other', 'normal', 'main', 'ココナッツと海老の風味を重ねる東南アジアの麺'),
(gen_random_uuid(), 'バインセオ',     'ばいんせお',        'other', 'normal', 'main', '米粉の生地を薄く焼いて具を包むベトナム料理'),
(gen_random_uuid(), 'ブンチャー',     'ぶんちゃー',        'other', 'normal', 'main', '焼いた肉をつけ汁と米麺で食べる。炭火の香りが要'),
(gen_random_uuid(), 'ガイヤーン',     'がいやーん',        'other', 'normal', 'main', 'スパイスに漬けた鶏をじっくり焼くタイの料理'),
(gen_random_uuid(), 'トムカーガイ',   'とむかーがい',      'other', 'normal', 'main', 'ココナッツミルクで鶏を煮る。酸味と辛味の調整が要る'),
(gen_random_uuid(), 'マッサマンカレー', 'まっさまんかれー',   'other', 'normal', 'main', 'じゃがいもとナッツを煮込む甘めのタイカレー'),
(gen_random_uuid(), 'サグカレー',     'さぐかれー',        'other', 'normal', 'main', 'ほうれん草をペーストにして煮込む'),
(gen_random_uuid(), 'ダルカレー',     'だるかれー',        'other', 'normal', 'main', '豆を煮崩して作る。肉を使わないので軽い'),
(gen_random_uuid(), 'チャナマサラ',   'ちゃなまさら',      'other', 'normal', 'main', 'ひよこ豆をスパイスで煮込む。作り置きに向く'),
(gen_random_uuid(), 'サモサ',        'さもさ',            'other', 'normal', 'side', '具を包んで揚げる。包み方に慣れが要る'),
(gen_random_uuid(), 'ファラフェル',   'ふぁらふぇる',      'other', 'normal', 'side', 'ひよこ豆をすり潰して揚げる。前日から豆を戻す'),
(gen_random_uuid(), 'シュクメルリ',   'しゅくめるり',      'other', 'normal', 'main', 'にんにくを効かせた鶏のクリーム煮。ジョージアの料理'),
(gen_random_uuid(), 'キョフテ',      'きょふて',          'other', 'normal', 'main', 'スパイスを練り込んだ挽き肉を焼くトルコの料理'),
(gen_random_uuid(), 'ジャークチキン',  'じゃーくちきん',     'other', 'normal', 'main', 'スパイスに漬け込んで焼くジャマイカの料理'),
(gen_random_uuid(), 'フェイジョアーダ', 'ふぇいじょあーだ',   'other', 'normal', 'main', '黒豆と肉を煮込むブラジルの家庭料理'),
(gen_random_uuid(), 'エンパナーダ',   'えんぱなーだ',      'other', 'normal', 'main', '具を生地で包んで焼く中南米のパイ'),
(gen_random_uuid(), 'チキンファヒータ', 'ちきんふぁひーた',   'other', 'normal', 'main', '焼いた肉と野菜をトルティーヤで巻いて食べる'),
(gen_random_uuid(), 'エンチラーダ',   'えんちらーだ',      'other', 'normal', 'main', '具を巻いたトルティーヤにソースをかけて焼く'),
(gen_random_uuid(), 'ピロシキ',      'ぴろしき',          'other', 'normal', 'main', '具を包んで揚げるロシアのパン。具は前日に作れる'),
(gen_random_uuid(), 'アドボ',        'あどぼ',            'other', 'normal', 'main', '酢と醤油で肉を煮込むフィリピンの家庭料理'),
(gen_random_uuid(), 'シニガン',      'しにがん',          'other', 'normal', 'main', '酸味の効いたフィリピンのスープ。野菜がたくさん取れる'),
(gen_random_uuid(), 'ナシチャンプル',  'なしちゃんぷる',     'other', 'normal', 'main', '複数のおかずをご飯に少しずつ盛る。品数を作る手間はある'),

-- ============ その他 × 手が込んだ ============
(gen_random_uuid(), 'ビリヤニ',      'びりやに',          'other', 'elaborate', 'main', '米と肉を層にして炊き上げる。スパイス配合が要'),
(gen_random_uuid(), 'サムゲタン',     'さむげたん',        'other', 'elaborate', 'main', '鶏を丸ごと薬膳と共に煮込む'),
(gen_random_uuid(), 'ムサカ',        'むさか',            'other', 'elaborate', 'main', '茄子と挽き肉を層にして焼くギリシャ料理'),
(gen_random_uuid(), 'タジン鍋',      'たじんなべ',        'other', 'elaborate', 'main', '専用鍋で蒸し煮にするモロッコ料理'),
(gen_random_uuid(), 'シュラスコ',     'しゅらすこ',        'other', 'elaborate', 'main', '塊肉を串に刺して炭火でじっくり焼く'),
(gen_random_uuid(), 'モレ・ポブラーノ', 'もれぽぶらーの',    'other', 'elaborate', 'main', '多数の唐辛子とチョコを使うメキシコのソース'),
(gen_random_uuid(), 'クスクス',      'くすくす',          'other', 'elaborate', 'main', '蒸したセモリナに煮込みを合わせる北アフリカ料理'),
(gen_random_uuid(), 'ボルシチ',      'ぼるしち',          'other', 'elaborate', 'main', 'ビーツと牛肉をじっくり煮込む'),
(gen_random_uuid(), 'ラムのロースト',  'らむのろーすと',     'other', 'elaborate', 'main', 'ハーブをまとわせて塊肉を焼き上げる'),
(gen_random_uuid(), 'セビーチェ',     'せびーちぇ',        'other', 'elaborate', 'main', '魚介を柑橘で締めるペルーの前菜。鮮度が命')
-- **upsert にする。** DO NOTHING（挿入のみ）だと、説明文やカナを直しても
-- 既にシード済みのDB（本番など）には永久に反映されない。
-- このファイルを「あるべき状態」の定義として扱い、再実行で追いつかせる。
--
-- ただし**名前の変更だけはこれでは直らない**（name がキーのため、旧行が残って
-- 新行が増える）。名前を変えるときはマイグレーションで対応すること。
ON CONFLICT (name) DO UPDATE SET
    name_kana   = EXCLUDED.name_kana,
    genre       = EXCLUDED.genre,
    difficulty  = EXCLUDED.difficulty,
    role        = EXCLUDED.role,
    description = EXCLUDED.description;
