/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 死活確認 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 稼働中 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menus/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 献立を1件提案する
         * @description ログイン中は直近履歴の献立を避け、提案結果を履歴に記録する。
         *     履歴を避けた結果0件になる場合は、避けずに提案する（spec.md 2.2 ルール3）。
         *     未認証でも利用できる。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 未指定と空文字はどちらも「絞り込まない」。 */
                    genre?: components["parameters"]["GenreQuery"];
                    /** @description 未指定と空文字はどちらも「絞り込まない」。 */
                    difficulty?: components["parameters"]["DifficultyQuery"];
                    /** @description **未指定は main（主菜）に絞る。** ジャンル・難易度と違い「すべて」ではない。 絞り込まない場合は all を明示する（spec.md 2.10）。 */
                    role?: components["parameters"]["RoleQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 提案された献立 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MenuResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description 条件に合う献立が無い */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menus/suggest-weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 1週間分（7日）の献立を提案する */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["WeeklyRequest"];
                };
            };
            responses: {
                /** @description 7日分の献立 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WeeklyResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description 条件に合う献立が足りない */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menus/reroll-day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 週間献立の指定日だけを引き直す
         * @description サーバは週の状態を持たない。現在の週の献立IDを呼び出し側が渡す。
         *     引き直した結果は履歴に記録しない（確定した献立ではないため）。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RerollRequest"];
                };
            };
            responses: {
                /** @description 引き直した1日分の献立 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MenuResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description 条件に合う献立が無い */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menus/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 献立の詳細を取得する */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 献立のID */
                    id: components["parameters"]["MenuIDPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 献立 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MenuResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menus/{id}/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 献立のレシピリンクを取得する
         * @description 外部の検索APIを使う。結果0件は障害ではないので 200 で空配列を返す。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 献立のID */
                    id: components["parameters"]["MenuIDPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description レシピリンク（最大3件） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecipesResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
                /** @description 外部の検索APIから結果を得られなかった */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menus/{id}/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 献立に必要な食材を取得する
         * @description 調味料は含まない（spec.md 14.4）。分量も持たない（14.2）。
         *     代表的な食材の例であり、実際の材料はレシピ元で確認する前提。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 献立のID */
                    id: components["parameters"]["MenuIDPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 食材の一覧（カテゴリ順→カナ順） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IngredientsResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menus/search-by-ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 手持ちの食材で作れる献立を探す
         * @description 選んだ食材を1つでも使う献立を、当てはまり具合とともに返す（spec.md 2.9 / 5.6）。
         *
         *     完全一致には絞らない。献立1件の食材は平均4.4種で、それを全部持っている
         *     状況はまれなため、絞ると候補がほぼ0件になる。各候補に不足食材を示すことで
         *     「あと2品買えば作れる」が分かるようにする。
         *
         *     並びは「不足の少ない順 → 一致の多い順 → カナ順」。上位20件まで。
         *     手持ちと1つも重ならない献立は返さない。未認証でも使える。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 手持ちの食材。1件以上。重複は1件として扱う。 */
                        ingredientIds: string[];
                    };
                };
            };
            responses: {
                /** @description 候補の献立 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MenuMatchesResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 食材マスタを全件取得する
         * @description 手持ちの食材を選ぶ画面の選択肢に使う（spec.md 2.9 / 5.6）。
         *     並びはカテゴリ順（野菜→肉→魚介→卵乳→主食→その他）、同カテゴリ内はカナ順。
         *     166件で固定的なため、ページングも検索クエリも設けない。
         *     未認証でも使える（検索と同じ扱い）。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 食材マスタ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IngredientsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shopping-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 複数の献立から買い物リストを作る
         * @description 週間献立はサーバに保存していないため、献立IDをリクエストで受け取る。
         *     同じ食材が複数の献立に出たら1件にまとめ、usedIn にその献立を並べる。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ShoppingListRequest"];
                };
            };
            responses: {
                /** @description 買い物リスト（カテゴリ順→カナ順） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ShoppingListResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** メールとパスワードで登録する */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CredentialsRequest"];
                };
            };
            responses: {
                /** @description 登録したユーザー。認証Cookieを設定する。 */
                201: {
                    headers: {
                        "Set-Cookie": components["headers"]["SetAuthCookies"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description メールアドレスが登録済み */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * メールとパスワードでログインする
         * @description 存在しないメールもパスワード違いも同じ 401 に丸める。
         *     どちらであるかを返すと、登録済みメールを推測できてしまうため。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CredentialsRequest"];
                };
            };
            responses: {
                /** @description ログインしたユーザー。認証Cookieを設定する。 */
                200: {
                    headers: {
                        "Set-Cookie": components["headers"]["SetAuthCookies"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * リフレッシュトークンでアクセストークンを再発行する
         * @description refresh_token Cookie を使う。このCookieは /api/v1/auth にのみ送られる。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 新しいアクセストークンをCookieに設定した */
                204: {
                    headers: {
                        "Set-Cookie": components["headers"]["SetAuthCookies"];
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ログアウトする */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 認証Cookieを破棄した */
                204: {
                    headers: {
                        "Set-Cookie": components["headers"]["SetAuthCookies"];
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google認証を開始する
         * @description Googleの同意画面へリダイレクトする。state と PKCE verifier を Cookie に置く。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Googleの認可エンドポイントへのリダイレクト */
                302: {
                    headers: {
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google認証のコールバック
         * @description state を定数時間で照合し、コードをトークンに交換する。
         *     メール未確認のGoogleアカウントは受け付けない（他人のメールでの乗っ取りを防ぐ）。
         */
        get: {
            parameters: {
                query: {
                    code: string;
                    state: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description フロントエンドへのリダイレクト。認証Cookieを設定する。 */
                302: {
                    headers: {
                        Location?: string;
                        "Set-Cookie": components["headers"]["SetAuthCookies"];
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 現在のユーザーを取得する */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 現在のユーザー */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/histories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 検索履歴を新しい順に取得する
         * @description 保持されるのは最新15件まで（超過分は自動削除される）。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 検索履歴 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HistoriesResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        /**
         * 検索履歴を全件削除する
         * @description 0件でも成功する（冪等）。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除した */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/histories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 検索履歴を1件削除する */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 履歴のID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除した */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                /** @description 他ユーザーの履歴 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * お気に入りを新しい順に取得する
         * @description 履歴と違い件数の上限が無く、自動削除もされない（spec.md 2.6）。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description お気に入り */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FavoritesResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** お気に入りに献立を追加する */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        menuId: string;
                    };
                };
            };
            responses: {
                /** @description 追加した */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            menuId: string;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                /** @description 同じ献立が既に登録されている */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/favorites/{menuId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * お気に入りから献立を外す
         * @description 自分の (ユーザー, 献立) の行だけを消すため、他人のお気に入りには到達できない。
         *     自分が登録していない献立は 403 ではなく 404 を返す
         *     （403 だと他人が何を登録しているかを漏らすため）。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    menuId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除した */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/weekly-menus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 保存した週間献立を新しい順に取得する
         * @description 中身の7日分を含めて返すため、「開く」ための個別取得は設けていない。
         *     上限が10件と小さいのでページングも設けず全件返す（spec.md 2.8 / 5.3）。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 保存した週間献立 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SavedWeeklyMenusResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * 組み立てた1週間分の献立を保存する
         * @description 7日分をひとまとまりで保存する（spec.md 2.8）。買い物の場で見返すのが主な用途。
         *
         *     保存できるのは1ユーザーあたり10件まで。上限に達した状態での保存は、
         *     古いものを押し出さず 409 で断る。履歴（FIFO）と違い保存は明示的な操作であり、
         *     黙って消えると保存という行為の意味が壊れるため。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 7日分ちょうど。day の重複は不可。 */
                        days: {
                            /** @description 起点からの通し番号（spec.md 13.3 の当日起点）。 */
                            day: number;
                            /** Format: uuid */
                            menuId: string;
                        }[];
                    };
                };
            };
            responses: {
                /** @description 保存した */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                /** @description 保存の上限（10件）に達している */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/weekly-menus/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 保存した週間献立を削除する
         * @description 自分の行だけを消すため、他人の保存には到達できない。
         *     他人のものを指した場合は 403 ではなく 404 を返す（403 だと保存の存在を明かすため）。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除した */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Genre: "japanese" | "western" | "chinese" | "other";
        /** @enum {string} */
        Difficulty: "easy" | "normal" | "elaborate";
        /**
         * @description 献立が一食の中で担う役割（spec.md 2.10）。
         * @enum {string}
         */
        Role: "main" | "side" | "soup";
        /**
         * @description 検索での役割の絞り込み。all は「絞り込まない」。 **省略時は main**で、ジャンル・難易度（省略時はすべて）と意味が違う。
         * @enum {string}
         */
        RoleFilter: "main" | "side" | "soup" | "all";
        /** @enum {string} */
        SearchMode: "single" | "weekly";
        Menu: {
            /** Format: uuid */
            id: string;
            name: string;
            genre: components["schemas"]["Genre"];
            difficulty: components["schemas"]["Difficulty"];
            role: components["schemas"]["Role"];
            description: string;
        };
        MenuResponse: {
            menu: components["schemas"]["Menu"];
        };
        WeeklyRequest: {
            genre?: components["schemas"]["Genre"] | null;
            difficulty?: components["schemas"]["Difficulty"] | null;
            role?: components["schemas"]["RoleFilter"] | null;
        };
        DayMenu: {
            day: number;
            menu: components["schemas"]["Menu"];
        };
        WeeklyResponse: {
            week: components["schemas"]["DayMenu"][];
        };
        RerollRequest: {
            /** @description 引き直す日。 */
            day: number;
            /** @description 現在の週の献立IDを day 順に並べたもの。 */
            week: string[];
            genre?: components["schemas"]["Genre"] | null;
            difficulty?: components["schemas"]["Difficulty"] | null;
            role?: components["schemas"]["RoleFilter"] | null;
        };
        Recipe: {
            title: string;
            /** Format: uri */
            url: string;
            domain: string;
            snippet: string;
        };
        RecipesResponse: {
            recipes: components["schemas"]["Recipe"][];
        };
        Ingredient: {
            /** Format: uuid */
            id: string;
            /** @example 玉ねぎ */
            name: string;
            /**
             * @description 一覧の並び順に使う
             * @example たまねぎ
             */
            nameKana: string;
            /**
             * @description 調味料の分類は持たない（spec.md 14.4）
             * @enum {string}
             */
            category: "vegetable" | "meat" | "seafood" | "dairy_egg" | "staple" | "other";
        };
        IngredientsResponse: {
            ingredients: components["schemas"]["Ingredient"][];
        };
        ShoppingListRequest: {
            /** @description 1〜7件。重複は1件として扱う */
            menuIds: string[];
        };
        ShoppingItem: {
            ingredient: components["schemas"]["Ingredient"];
            /**
             * @description その食材を使う献立。分量を持たない設計の補償として、
             *     何のために買うかを利用者が判断できるようにする。
             */
            usedIn: {
                /** Format: uuid */
                id: string;
                name: string;
            }[];
        };
        ShoppingListResponse: {
            items: components["schemas"]["ShoppingItem"][];
        };
        CredentialsRequest: {
            /** Format: email */
            email: string;
            /** @description 8文字以上・72バイト以下。 */
            password: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
            /**
             * @description 契約プラン。上限そのものは返さない。フロントが件数を持つと
             *     サーバとの二重管理になるため、上限に達したことは 409 の本文で伝える。
             * @enum {string}
             */
            plan: "free" | "premium";
        };
        UserResponse: {
            user: components["schemas"]["User"];
        };
        HistoryItem: {
            /** Format: uuid */
            id: string;
            menu: components["schemas"]["Menu"];
            searchMode: components["schemas"]["SearchMode"];
            /** Format: date-time */
            searchedAt: string;
        };
        HistoriesResponse: {
            histories: components["schemas"]["HistoryItem"][];
        };
        FavoriteItem: {
            menu: components["schemas"]["Menu"];
            /** Format: date-time */
            createdAt: string;
        };
        FavoritesResponse: {
            favorites: components["schemas"]["FavoriteItem"][];
        };
        /**
         * @description 保存した週間献立1件。中身の7日分をここに含めるため、「開く」ための
         *     個別取得は要らない。1日分の形は週間献立の提案と同じ DayMenu。
         */
        SavedWeeklyMenu: {
            /** Format: uuid */
            id: string;
            days: components["schemas"]["DayMenu"][];
            /** Format: date-time */
            createdAt: string;
        };
        SavedWeeklyMenusResponse: {
            weeklyMenus: components["schemas"]["SavedWeeklyMenu"][];
        };
        /**
         * @description 手持ちの食材に対する献立1件の当てはまり具合。
         *     matched は手持ちと重なった食材、missing は買い足しが要る食材。
         */
        MenuMatch: {
            menu: components["schemas"]["Menu"];
            matched: components["schemas"]["Ingredient"][];
            missing: components["schemas"]["Ingredient"][];
        };
        MenuMatchesResponse: {
            matches: components["schemas"]["MenuMatch"][];
        };
        /** @description RFC 7807 の Problem Details。 */
        Problem: {
            /**
             * Format: uri
             * @description エラー種別を識別するURI。
             */
            type: string;
            /** @description 人間が読める短い要約。同じ type なら同じ title。 */
            title: string;
            status: number;
            /** @description この発生に固有の説明。 */
            detail?: string;
        };
    };
    responses: {
        /** @description リクエストが不正 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 認証が必要、または認証に失敗した */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 対象が存在しない */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description 未指定と空文字はどちらも「絞り込まない」。 */
        GenreQuery: components["schemas"]["Genre"];
        /** @description 未指定と空文字はどちらも「絞り込まない」。 */
        DifficultyQuery: components["schemas"]["Difficulty"];
        /** @description **未指定は main（主菜）に絞る。** ジャンル・難易度と違い「すべて」ではない。 絞り込まない場合は all を明示する（spec.md 2.10）。 */
        RoleQuery: components["schemas"]["RoleFilter"];
        /** @description 献立のID */
        MenuIDPath: string;
    };
    requestBodies: never;
    headers: {
        /**
         * @description access_token（15分・path=/）と refresh_token（30日・path=/api/v1/auth）。
         *     いずれも HttpOnly / Secure / SameSite=Lax。
         */
        SetAuthCookies: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
