/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 死活確認 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 稼働中 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menus/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 献立を1件提案する
         * @description ログイン中は直近履歴の献立を避け、提案結果を履歴に記録する。
         *     履歴を避けた結果0件になる場合は、避けずに提案する（spec.md 2.2 ルール3）。
         *     未認証でも利用できる。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 未指定と空文字はどちらも「絞り込まない」。 */
                    genre?: components["parameters"]["GenreQuery"];
                    /** @description 未指定と空文字はどちらも「絞り込まない」。 */
                    difficulty?: components["parameters"]["DifficultyQuery"];
                    /** @description **未指定は main（主菜）に絞る。** ジャンル・難易度と違い「すべて」ではない。 絞り込まない場合は all を明示する（spec.md 2.10）。 */
                    role?: components["parameters"]["RoleQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 提案された献立 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MenuResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description 条件に合う献立が無い */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menus/suggest-weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 1週間分（7日）の献立を提案する
         * @description premium 限定（spec.md 2.2 / 2.11、週間premium再編設計）。
         *     未ログインは 401、ログイン済みの free は 403。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["WeeklyRequest"];
                };
            };
            responses: {
                /** @description 7日分の献立 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WeeklyResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                /** @description プレミアムプランが必要 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                /** @description 条件に合う献立が足りない */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menus/reroll-day": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 週間献立の指定日だけを引き直す
         * @description サーバは週の状態を持たない。現在の週の献立IDを呼び出し側が渡す。
         *     引き直した結果は履歴に記録しない（確定した献立ではないため）。
         *
         *     premium 限定（spec.md 2.2 / 2.11、週間premium再編設計）。
         *     未ログインは 401、ログイン済みの free は 403。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RerollRequest"];
                };
            };
            responses: {
                /** @description 引き直した1日分の献立 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MenuResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                /** @description プレミアムプランが必要 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                /** @description 条件に合う献立が無い */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menus/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 献立の詳細を取得する */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 献立のID */
                    id: components["parameters"]["MenuIDPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 献立 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MenuResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menus/{id}/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 献立のレシピリンクを取得する
         * @description 外部の検索APIを使う。結果0件は障害ではないので 200 で空配列を返す。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 献立のID */
                    id: components["parameters"]["MenuIDPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description レシピリンク（最大3件） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecipesResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
                /** @description 外部の検索APIから結果を得られなかった */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menus/{id}/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 献立に必要な食材を取得する
         * @description 調味料は含まない（spec.md 14.4）。分量も持たない（14.2）。
         *     代表的な食材の例であり、実際の材料はレシピ元で確認する前提。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 献立のID */
                    id: components["parameters"]["MenuIDPath"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 食材の一覧（カテゴリ順→カナ順） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IngredientsResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menus/search-by-ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 手持ちの食材で作れる献立を探す
         * @description 選んだ食材を1つでも使う献立を、当てはまり具合とともに返す（spec.md 2.9 / 5.6）。
         *
         *     既定では完全一致に絞らない。献立1件の食材は平均4.4種で、それを全部持っている
         *     状況はまれなため。各候補に不足食材を示し「あと2品買えば作れる」が分かるようにする。
         *
         *     `onlyMakeable: true` のときは不足0の献立だけを返す。手持ちを20種ほど
         *     選べば30件前後が該当する。0件だった場合に限り、`nearMisses` に
         *     「あと1品買えば作れる」候補を添える。
         *
         *     並びは `sort` で選ぶ。上位20件まで（`matches` / `nearMisses` それぞれ）。
         *     手持ちと1つも重ならない献立は返さない。未認証でも使える。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 手持ちの食材。1件以上。重複は1件として扱う。 */
                        ingredientIds: string[];
                        /**
                         * @description true のとき、不足のある献立を返さない（この中だけで作れるもの）。
                         *     省略時は false で、従来どおり不足を許す。
                         * @default false
                         */
                        onlyMakeable?: boolean;
                        /**
                         * @description missing_asc … 不足の少ない順 → 一致の多い順 → カナ順（既定）
                         *     matched_desc … 一致の多い順 → 不足の少ない順 → カナ順
                         *     未知の値は 400。既定に丸めない。
                         * @default missing_asc
                         * @enum {string}
                         */
                        sort?: "missing_asc" | "matched_desc";
                    };
                };
            };
            responses: {
                /** @description 候補の献立 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MenuMatchesResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 食材マスタを全件取得する
         * @description 手持ちの食材を選ぶ画面の選択肢に使う（spec.md 2.9 / 5.6）。
         *     並びはカテゴリ順（野菜→肉→魚介→卵乳→主食→その他）、同カテゴリ内はカナ順。
         *     166件で固定的なため、ページングも検索クエリも設けない。
         *     未認証でも使える（検索と同じ扱い）。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 食材マスタ */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IngredientsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingredients/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 手持ちの食材のテキストを食材に対応づける
         * @description 自由記述で書かれた食材（「豚こま、玉ねぎ、マツタケ」）を食材マスタに
         *     対応づける。166種をカテゴリから探してチェックする操作は、冷蔵庫を
         *     開けながらやるには重いため、その前段として自由記述を受ける。
         *
         *     解決は ①食材マスタとの完全一致 → ②解決キャッシュ → ③LLM の順。
         *     全語が①で解ければLLMは呼ばない。
         *
         *     **LLM が落ちても 502 にはしない。** ①②で解けた分を 200 で返し、
         *     degraded を立てる。呼び出し側は解釈結果を利用者に見せて確認させる。
         *
         *     対応づかなかった語は unresolved に入る。検索には使われない。
         *     未認証でも使える（検索と同じ扱い）。
         *
         *     「読み取る」は LLM を呼ぶため日次の上限がある（非ログインはIP単位）。
         *     上限に達しても 502 にはせず、①②で解けた分を 200 で返して
         *     degraded と degradedReason を立てる。チェックボックスから選ぶ経路は
         *     上限の対象外で、いつでも使える。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description 区切りは「、」「,」「，」改行・空白・「・」。
                         *     最大200文字、語は最大20件。
                         * @example 豚こま、玉ねぎ、マツタケ
                         */
                        text: string;
                    };
                };
            };
            responses: {
                /** @description 解決結果（一部しか解けなくても200） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResolveResult"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shopping-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 複数の献立から買い物リストを作る
         * @description 週間献立はサーバに保存していないため、献立IDをリクエストで受け取る。
         *     同じ食材が複数の献立に出たら1件にまとめ、usedIn にその献立を並べる。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ShoppingListRequest"];
                };
            };
            responses: {
                /** @description 買い物リスト（カテゴリ順→カナ順） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ShoppingListResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** メールとパスワードで登録する */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CredentialsRequest"];
                };
            };
            responses: {
                /** @description 登録したユーザー。認証Cookieを設定する。 */
                201: {
                    headers: {
                        "Set-Cookie": components["headers"]["SetAuthCookies"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description メールアドレスが登録済み */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * メールとパスワードでログインする
         * @description 存在しないメールもパスワード違いも同じ 401 に丸める。
         *     どちらであるかを返すと、登録済みメールを推測できてしまうため。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CredentialsRequest"];
                };
            };
            responses: {
                /** @description ログインしたユーザー。認証Cookieを設定する。 */
                200: {
                    headers: {
                        "Set-Cookie": components["headers"]["SetAuthCookies"];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * リフレッシュトークンでアクセストークンを再発行する
         * @description refresh_token Cookie を使う。このCookieは /api/v1/auth にのみ送られる。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 新しいアクセストークンをCookieに設定した */
                204: {
                    headers: {
                        "Set-Cookie": components["headers"]["SetAuthCookies"];
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** ログアウトする */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 認証Cookieを破棄した */
                204: {
                    headers: {
                        "Set-Cookie": components["headers"]["SetAuthCookies"];
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google認証を開始する
         * @description Googleの同意画面へリダイレクトする。state と PKCE verifier を Cookie に置く。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Googleの認可エンドポイントへのリダイレクト */
                302: {
                    headers: {
                        Location?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Google認証のコールバック
         * @description state を定数時間で照合し、コードをトークンに交換する。
         *     メール未確認のGoogleアカウントは受け付けない（他人のメールでの乗っ取りを防ぐ）。
         */
        get: {
            parameters: {
                query: {
                    code: string;
                    state: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description フロントエンドへのリダイレクト。認証Cookieを設定する。 */
                302: {
                    headers: {
                        Location?: string;
                        "Set-Cookie": components["headers"]["SetAuthCookies"];
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 現在のユーザーを取得する */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 現在のユーザー */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/histories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 検索履歴を新しい順に取得する
         * @description 保持されるのは最新15件まで（超過分は自動削除される）。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 検索履歴 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HistoriesResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        /**
         * 検索履歴を全件削除する
         * @description 0件でも成功する（冪等）。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除した */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/histories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 検索履歴を1件削除する */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 履歴のID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除した */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                /** @description 他ユーザーの履歴 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * お気に入りを新しい順に取得する
         * @description 履歴と違い件数の上限が無く、自動削除もされない（spec.md 2.6）。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description お気に入り */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FavoritesResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /** お気に入りに献立を追加する */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        menuId: string;
                    };
                };
            };
            responses: {
                /** @description 追加した */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            menuId: string;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
                /** @description 同じ献立が既に登録されている */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/favorites/{menuId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * お気に入りから献立を外す
         * @description 自分の (ユーザー, 献立) の行だけを消すため、他人のお気に入りには到達できない。
         *     自分が登録していない献立は 403 ではなく 404 を返す
         *     （403 だと他人が何を登録しているかを漏らすため）。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    menuId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除した */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/weekly-menus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 保存した週間献立を新しい順に取得する
         * @description 中身の7日分を含めて返すため、「開く」ための個別取得は設けていない。
         *     上限が最大でも50件と小さいのでページングも設けず全件返す（spec.md 2.8 / 2.11 / 5.3）。
         *
         *     premium 限定（spec.md 2.8 / 2.11、週間premium再編設計）。free は保存済みの週が
         *     残っていても一覧が 403 になる（grandfather しない）。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 保存した週間献立 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SavedWeeklyMenusResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description プレミアムプランが必要 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        /**
         * 組み立てた1週間分の献立を保存する
         * @description 7日分をひとまとまりで保存する（spec.md 2.8）。買い物の場で見返すのが主な用途。
         *
         *     保存できる件数は全員50件（spec.md 2.11）。
         *     件数は応答に含めず、上限に達したときの 409 の detail に文言として入れて返す。
         *     クライアントが件数を持つとサーバとの二重管理になるため。
         *
         *     上限に達した状態での保存は、古いものを押し出さず 409 で断る。
         *     履歴（FIFO）と違い保存は明示的な操作であり、
         *     黙って消えると保存という行為の意味が壊れるため。
         *
         *     premium 限定（spec.md 2.8 / 2.11、週間premium再編設計）。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 7日分ちょうど。day の重複は不可。 */
                        days: {
                            /** @description 起点からの通し番号（spec.md 13.3 の当日起点）。 */
                            day: number;
                            /** Format: uuid */
                            menuId: string;
                        }[];
                    };
                };
            };
            responses: {
                /** @description 保存した */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                /** @description プレミアムプランが必要 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                404: components["responses"]["NotFound"];
                /**
                 * @description 保存の上限に達している。件数はハードコードを避けるため、
                 *     detail に「保存できるのはN件までです」を入れて返す。
                 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/weekly-menus/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 保存した週間献立を削除する
         * @description 自分の行だけを消すため、他人の保存には到達できない。
         *     他人のものを指した場合は 403 ではなく 404 を返す（403 だと保存の存在を明かすため）。
         *
         *     premium 限定（spec.md 2.8 / 2.11、週間premium再編設計）。
         *     こちらの 403 はプレミアムプランが必要であることを示す（他人の保存の 403 とは別の意味）。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 削除した */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                /** @description プレミアムプランが必要 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/weekly-menus/{id}/shopping-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 保存済みの週の買い物リストを取得する
         * @description 保存済みの週間献立から買い物リストを導出し、差分（チェック・手動品目・非表示）を
         *     重ねて返す。差分の重ね合わせはサーバで行い、フロントには最終形だけを渡す。
         *     他人の週は 404。
         *
         *     premium 限定（spec.md 2.8 / 2.11、週間premium再編設計）。従来は free でも呼べたが、
         *     週間まわり一式が premium の傘に入ったため free は 403 になる。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 差分適用後の買い物リスト（カテゴリ順→カナ順） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SavedShoppingListResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description プレミアムプランが必要 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /**
         * 保存済みの週の買い物リストの差分を置き換える
         * @description チェック状態・手動品目・非表示を overlay 全体として一括置換する（設計 3.5）。
         *     品目単位の部分更新はしない。free は 403。手動品目が上限を超えると 409。
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ShoppingListOverridesRequest"];
                };
            };
            responses: {
                /** @description 置き換えた */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
                401: components["responses"]["Unauthorized"];
                /** @description プレミアムプランが必要 */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                404: components["responses"]["NotFound"];
                /** @description 手動品目が上限に達している */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * プランの公開情報を取得する
         * @description 料金ページ（/pricing）に出す、誰にでも同じプラン情報。
         *     料金の提示は未ログインにも見せるため認証を要さない。
         *     個人に依る値（トライアル適格・初回課金日）は含めない。それらは
         *     /billing/preview（要認証・特商法12条の6の申込確認）が返す。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description プランの公開情報 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BillingPlanResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 申込確認画面の表示値を取得する
         * @description 自前の申込確認画面（特商法12条の6）に出す価格・トライアル・初回課金日を返す。
         *     トライアルは初回加入のみ（過去に加入行があれば trialEligible は false）。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 申込確認画面の表示値 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BillingPreviewResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/checkout-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stripe Checkout セッションを作成する
         * @description Stripe Checkout（ホスト型。カード情報は自社を通さない）のセッションURLを返す。
         *     フロントはこのURLへリダイレクトする。加入状態の真実は Webhook が持つため、
         *     このAPI自身は subscriptions を更新しない。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Checkout セッションのURL */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CheckoutSessionResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description 既にプレミアムに加入している */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 現在のプラン状態を取得する
         * @description アカウント設定 > プランの管理 画面の表示値。
         *     加入状態の真実の源は Webhook が更新する subscriptions で、このAPIは読むだけ。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 現在のプラン状態 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubscriptionResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/portal-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stripe 顧客ポータルのセッションを作成する
         * @description Stripe 顧客ポータル（ホスト型）のセッションURLを返す。フロントはこのURLへ
         *     リダイレクトする。解約・カード変更・請求履歴の閲覧はポータル側で行われ、
         *     その結果は既存の Webhook（/billing/webhook）が同期する。このAPI自身は
         *     subscriptions を更新しない。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 顧客ポータルセッションのURL */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PortalSessionResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Stripe 顧客が紐づいていない（手動付与・未加入） */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stripe Webhook を受け取る
         * @description Stripe が直接叩くエンドポイント。クライアントから呼ぶものではない。
         *     認証Cookieは付かず、`Stripe-Signature` ヘッダの署名検証で保護する。
         *     加入状態（subscriptions）の真実の源はここで、preview / checkout-session は
         *     表示・申込導線に過ぎない。
         *
         *     Stripe は RFC 7807 を解釈しないため、problem+json ではなく素の応答を返す。
         *     署名不正・本文解釈失敗は 400（Stripeに再送させない）、こちら側の不調
         *     （DB障害など）は 500（Stripeに再送してほしい）。
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Stripe が発行する署名。ペイロードの改竄・偽装元を検証する。 */
                    "Stripe-Signature": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description 同期した（対象外イベントも200で受理する） */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 署名不正、または本文を解釈できない */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Genre: "japanese" | "western" | "chinese" | "other";
        /** @enum {string} */
        Difficulty: "easy" | "normal" | "elaborate";
        /**
         * @description 献立が一食の中で担う役割（spec.md 2.10）。
         * @enum {string}
         */
        Role: "main" | "side" | "soup";
        /**
         * @description 検索での役割の絞り込み。all は「絞り込まない」。 **省略時は main**で、ジャンル・難易度（省略時はすべて）と意味が違う。
         * @enum {string}
         */
        RoleFilter: "main" | "side" | "soup" | "all";
        /** @enum {string} */
        SearchMode: "single" | "weekly";
        Menu: {
            /** Format: uuid */
            id: string;
            name: string;
            genre: components["schemas"]["Genre"];
            difficulty: components["schemas"]["Difficulty"];
            role: components["schemas"]["Role"];
            description: string;
        };
        MenuResponse: {
            menu: components["schemas"]["Menu"];
        };
        WeeklyRequest: {
            genre?: components["schemas"]["Genre"] | null;
            difficulty?: components["schemas"]["Difficulty"] | null;
            role?: components["schemas"]["RoleFilter"] | null;
        };
        DayMenu: {
            day: number;
            menu: components["schemas"]["Menu"];
        };
        WeeklyResponse: {
            week: components["schemas"]["DayMenu"][];
        };
        RerollRequest: {
            /** @description 引き直す日。 */
            day: number;
            /** @description 現在の週の献立IDを day 順に並べたもの。 */
            week: string[];
            genre?: components["schemas"]["Genre"] | null;
            difficulty?: components["schemas"]["Difficulty"] | null;
            role?: components["schemas"]["RoleFilter"] | null;
        };
        Recipe: {
            title: string;
            /** Format: uri */
            url: string;
            domain: string;
            snippet: string;
        };
        RecipesResponse: {
            recipes: components["schemas"]["Recipe"][];
        };
        Ingredient: {
            /** Format: uuid */
            id: string;
            /** @example 玉ねぎ */
            name: string;
            /**
             * @description 一覧の並び順に使う
             * @example たまねぎ
             */
            nameKana: string;
            /**
             * @description 調味料の分類は持たない（spec.md 14.4）
             * @enum {string}
             */
            category: "vegetable" | "meat" | "seafood" | "dairy_egg" | "staple" | "other";
        };
        IngredientsResponse: {
            ingredients: components["schemas"]["Ingredient"][];
        };
        ResolvedWord: {
            /**
             * @description 利用者が書いた**元の語**（正規化前）。「マツタケ は登録がありません」と
             *     出すとき、書いた通りの文字列の方が伝わるため。
             * @example 豚こま
             */
            word: string;
            ingredient: components["schemas"]["Ingredient"];
        };
        ResolveResult: {
            /** @description 食材に対応づいた語。0件でも null にせず空配列を返す。 */
            resolved: components["schemas"]["ResolvedWord"][];
            /**
             * @description マスタに無かった語（元の語）。検索には使われない。
             * @example [
             *       "マツタケ"
             *     ]
             */
            unresolved: string[];
            /**
             * @description LLM への問い合わせをスキップしたか。立っていても①②で解けた分は
             *     resolved に入っている。画面は「一部だけ読み取れました」と伝える。
             */
            degraded: boolean;
            /**
             * @description 縮退した理由。degraded が false なら出さない。
             *     画面はこれで文言を選ぶ。llm_error と counter_unavailable は
             *     利用者から見れば同じ「今うまく読めない」なので同じ文言を出す。
             * @enum {string}
             */
            degradedReason?: "llm_error" | "counter_unavailable" | "anon_daily_limit" | "user_daily_limit" | "service_daily_limit";
        };
        ShoppingListRequest: {
            /** @description 1〜7件。重複は1件として扱う */
            menuIds: string[];
        };
        ShoppingItem: {
            ingredient: components["schemas"]["Ingredient"];
            /**
             * @description その食材を使う献立。分量を持たない設計の補償として、
             *     何のために買うかを利用者が判断できるようにする。
             */
            usedIn: {
                /** Format: uuid */
                id: string;
                name: string;
            }[];
        };
        ShoppingListResponse: {
            items: components["schemas"]["ShoppingItem"][];
        };
        /**
         * @description 差分行の由来。derived=献立由来 / manual=手動追加。
         * @enum {string}
         */
        Origin: "derived" | "manual";
        SavedShoppingItem: {
            name: string;
            /**
             * @description 調味料の分類は持たない（spec.md 14.4）
             * @enum {string}
             */
            category: "vegetable" | "meat" | "seafood" | "dairy_egg" | "staple" | "other";
            origin: components["schemas"]["Origin"];
            checked: boolean;
            /** @description 利用者が消した導出品目であることを表す。表示からは外すが、 次回 PUT で overlay 全体を再構築できるよう GET には含める。 */
            hidden: boolean;
            /** @description その食材を使う献立。手動品目では空。 */
            usedIn: {
                /** Format: uuid */
                id: string;
                name: string;
            }[];
        };
        SavedShoppingListResponse: {
            items: components["schemas"]["SavedShoppingItem"][];
        };
        ShoppingListOverridesRequest: {
            /** @description overlay 全体。導出品目のチェック/非表示と、手動品目を並べる。 */
            items: {
                name: string;
                /**
                 * @description 調味料の分類は持たない（spec.md 14.4）
                 * @enum {string}
                 */
                category: "vegetable" | "meat" | "seafood" | "dairy_egg" | "staple" | "other";
                origin: components["schemas"]["Origin"];
                checked: boolean;
                hidden: boolean;
            }[];
        };
        CredentialsRequest: {
            /** Format: email */
            email: string;
            /** @description 8文字以上・72バイト以下。 */
            password: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
            /**
             * @description 契約プラン。上限そのものは返さない。フロントが件数を持つと
             *     サーバとの二重管理になるため、上限に達したことは 409 の本文で伝える。
             * @enum {string}
             */
            plan: "free" | "premium";
        };
        UserResponse: {
            user: components["schemas"]["User"];
        };
        HistoryItem: {
            /** Format: uuid */
            id: string;
            menu: components["schemas"]["Menu"];
            searchMode: components["schemas"]["SearchMode"];
            /** Format: date-time */
            searchedAt: string;
        };
        HistoriesResponse: {
            histories: components["schemas"]["HistoryItem"][];
        };
        FavoriteItem: {
            menu: components["schemas"]["Menu"];
            /** Format: date-time */
            createdAt: string;
        };
        FavoritesResponse: {
            favorites: components["schemas"]["FavoriteItem"][];
        };
        /**
         * @description 保存した週間献立1件。中身の7日分をここに含めるため、「開く」ための
         *     個別取得は要らない。1日分の形は週間献立の提案と同じ DayMenu。
         */
        SavedWeeklyMenu: {
            /** Format: uuid */
            id: string;
            days: components["schemas"]["DayMenu"][];
            /** Format: date-time */
            createdAt: string;
        };
        SavedWeeklyMenusResponse: {
            weeklyMenus: components["schemas"]["SavedWeeklyMenu"][];
        };
        /**
         * @description 手持ちの食材に対する献立1件の当てはまり具合。
         *     matched は手持ちと重なった食材、missing は買い足しが要る食材。
         */
        MenuMatch: {
            menu: components["schemas"]["Menu"];
            matched: components["schemas"]["Ingredient"][];
            missing: components["schemas"]["Ingredient"][];
        };
        MenuMatchesResponse: {
            matches: components["schemas"]["MenuMatch"][];
            /**
             * @description あと1品買えば作れる候補。onlyMakeable が true で matches が
             *     0件のときだけ埋まる。それ以外は常に空配列。
             */
            nearMisses: components["schemas"]["MenuMatch"][];
        };
        /** @description プランの公開情報（誰にでも同じ。/pricing が使う）。 */
        BillingPlanResponse: {
            /**
             * @description 月額料金（最小単位。currency=jpy なら円）。
             * @example 300
             */
            price: number;
            /** @example jpy */
            currency: string;
            /**
             * @description トライアル期間の日数。
             * @example 5
             */
            trialDays: number;
        };
        /** @description 申込確認画面（特商法12条の6）の表示値。 */
        BillingPreviewResponse: {
            /**
             * @description 月額料金（最小単位。currency=jpy なら円）。
             * @example 300
             */
            price: number;
            /** @example jpy */
            currency: string;
            /**
             * @description トライアル期間の日数。
             * @example 5
             */
            trialDays: number;
            /** @description 初回加入なら true。過去に加入行があれば false（トライアルは初回のみ）。 */
            trialEligible: boolean;
            /**
             * Format: date-time
             * @description 初回の課金日。トライアル適格ならトライアル終了日、そうでなければ現在時刻。
             */
            firstBillingAt: string;
            /**
             * @description 解約・プラン変更の導線名（アカウント設定 > プランの管理）。
             * @example アカウント設定 > プランの管理
             */
            planManagementPath: string;
        };
        CheckoutSessionResponse: {
            /**
             * Format: uri
             * @description Stripe Checkout（ホスト型）のセッションURL。フロントはここへリダイレクトする。
             */
            url: string;
        };
        /** @description アカウント設定 > プランの管理 画面の表示値。 */
        SubscriptionResponse: {
            /**
             * @description 現在のプラン。
             * @example premium
             */
            plan: string;
            /**
             * @description 加入状態（Stripe の subscription status、free なら `none`）。
             * @example active
             */
            status: string;
            /**
             * Format: date-time
             * @description 現在の請求期間の終了日時。free、または未加入なら null。
             */
            currentPeriodEnd: string | null;
            /** @description 期末解約が予約されているか（顧客ポータルで解約すると true になる）。 */
            cancelAtPeriodEnd: boolean;
            /** @description Stripe 顧客が紐づいているか。false なら手動付与や未加入で、プランの管理ボタンは出さない。 */
            hasPortal: boolean;
        };
        PortalSessionResponse: {
            /**
             * Format: uri
             * @description Stripe 顧客ポータル（ホスト型）のセッションURL。フロントはここへリダイレクトする。
             */
            url: string;
        };
        /** @description RFC 7807 の Problem Details。 */
        Problem: {
            /**
             * Format: uri
             * @description エラー種別を識別するURI。
             */
            type: string;
            /** @description 人間が読める短い要約。同じ type なら同じ title。 */
            title: string;
            status: number;
            /** @description この発生に固有の説明。 */
            detail?: string;
        };
    };
    responses: {
        /** @description リクエストが不正 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 認証が必要、または認証に失敗した */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description 対象が存在しない */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description 未指定と空文字はどちらも「絞り込まない」。 */
        GenreQuery: components["schemas"]["Genre"];
        /** @description 未指定と空文字はどちらも「絞り込まない」。 */
        DifficultyQuery: components["schemas"]["Difficulty"];
        /** @description **未指定は main（主菜）に絞る。** ジャンル・難易度と違い「すべて」ではない。 絞り込まない場合は all を明示する（spec.md 2.10）。 */
        RoleQuery: components["schemas"]["RoleFilter"];
        /** @description 献立のID */
        MenuIDPath: string;
    };
    requestBodies: never;
    headers: {
        /**
         * @description access_token（15分・path=/）と refresh_token（30日・path=/api/v1/auth）。
         *     いずれも HttpOnly / Secure / SameSite=Lax。
         */
        SetAuthCookies: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
